#!/usr/bin/env python3
"""Render cross-implementation-results.json into the Markdown tables of
cross-implementation-tables.md. The tables are generated, never edited by hand.

Usage: render_matrix.py <results.json> <output.md>
"""
import json
import sys

COIN = 100000000
NAMES = {"C": "C", "A": "A", "L": "L", "test": "hand-built"}


def rin(value):
    if value is None:
        return ""
    return ("%.8f" % (value / COIN)).rstrip("0").rstrip(".")


def verdict(e):
    if e["verdict"] == "accepted":
        if e.get("reason") == "inconclusive":
            return "accepted (valid side branch)"
        if e.get("reason") == "duplicate":
            return "accepted (already known)"
        return "accepted"
    return "**rejected**: `%s`" % e["reason"]


def main():
    data = json.load(open(sys.argv[1], encoding="utf8"))
    rec = data["records"]
    out = []
    w = out.append
    w("# Cross-implementation results — generated tables\n")
    w("Generated by `scripts/render_matrix.py` from `cross-implementation-results.json`")
    w("(run: %s, %s – %s). Do not edit by hand. Heights are regtest heights: the transition" % (data["label"], data["started"], data["finished"]))
    w("height is 840. C, A and L are defined in [`cross-implementation.md`](cross-implementation.md).\n")

    w("## Implementations as they identified themselves\n")
    w("| | User agent | Protocol version | Regtest genesis | Extra options |")
    w("|---|---|---|---|---|")
    for k in ("C", "A", "L"):
        i = data["implementations"][k]
        w("| %s | `%s` | %s | `%s` | %s |" % (k, i["subversion"], i["protocolversion"], i["genesis"], " ".join("`%s`" % a for a in i["extra_args"]) or "none"))
    w("")

    w("## 1. Blocks each implementation mined on its own branch\n")
    w("| Producer | Height | Block version | Coinbase claim (RIN) | Transactions | Coinbase scriptSig |")
    w("|---|---|---|---|---|---|")
    for e in rec:
        if e.get("kind") == "own-block" and e["scenario"] == "1":
            w("| %s | %s | `%s` | %s | %s | `%s` |" % (e["producer"], e["height"], e["version"], rin(e["coinbase_value"]), e["ntx"], e["coinbase_scriptsig"]))
    w("")

    w("## 2. Producer × validator: blocks\n")
    w("Every block was mined by the producer's own miner with the full reward and handed to the validator,")
    w("which started from the common chain (height 835), in height order.\n")
    w("| Producer → validator | Height | What the block is | Claim (RIN) | Verdict of the validator |")
    w("|---|---|---|---|---|")
    labels = {
        "blocks below the transition height": "empty, below the transition height",
        "first block at the transition height (empty)": "empty, at the transition height",
        "empty blocks after it": "empty, after it",
        "block with the producer's first ordinary transaction": "with the producer's first ordinary transaction",
        "blocks after it": "empty, after that",
    }
    for e in rec:
        if e.get("kind") == "block" and e["scenario"] in ("1", "2", "3") and e["step"] in labels:
            w("| %s → %s | %s | %s | %s | %s |" % (e["producer"], e["validator"], e["height"], labels[e["step"]], rin(e["coinbase_value"]), verdict(e)))
    w("")
    w("Where each validator ended up after the producer's whole branch:\n")
    w("| Producer → validator | Validator's final height | Follows the producer's tip |")
    w("|---|---|---|")
    for e in rec:
        if e.get("kind") == "state" and e["scenario"] == "2":
            w("| %s → %s | %s | %s |" % (e["producer"], e["validator"], e["height"], "yes" if e["follows_producer"] else "no"))
    w("")

    w("## 3. Producer × validator: transactions\n")
    w("An ordinary wallet payment of the producer, judged by each validator on the validator's own valid chain at")
    w("the same height. *Mempool* is `testmempoolaccept` (policy and consensus); *block* is `generateblock` with")
    w("that transaction (consensus only).\n")
    w("| Signed | Producer → validator | Mempool | Block |")
    w("|---|---|---|---|")
    pending = {}
    for e in rec:
        if e.get("kind", "").startswith("tx-"):
            key = (e["step"], e["producer"], e["validator"])
            pending.setdefault(key, {})[e["kind"]] = e
    for (step, p, v), d in pending.items():
        when = "below the transition height" if "below" in step else "above the transition height"
        w("| %s | %s → %s | %s | %s |" % (when, p, v, verdict(d["tx-mempool"]), verdict(d["tx-block"])))
    w("")

    for scen, title in (("4", "4. A transaction of A on a short branch, and a stronger empty branch of C"),
                        ("5", "5. A transaction of C, and a stronger empty branch of A"),
                        ("6", "6. L mines the block at the transition height"),
                        ("7", "7. Empty descendants of an invalid block")):
        w("## %s\n" % title)
        w("| Step | Who → whom | Height | Claim (RIN) | Transactions | Result |")
        w("|---|---|---|---|---|---|")
        for e in rec:
            if e["scenario"] != scen:
                continue
            if e.get("kind") == "block":
                w("| %s | %s → %s | %s | %s | %s | %s%s |" % (e["step"], NAMES[e["producer"]], e["validator"], e["height"], rin(e.get("coinbase_value")), e.get("ntx", ""), verdict(e), "; new tip" if e.get("became_tip") else ""))
            elif e.get("kind") == "own-block":
                extra = "; builds on L's block" if e.get("builds_on_l") else ""
                w("| %s | %s mines | %s | %s | %s | block version `%s`%s |" % (e["step"], e["producer"], e["height"], rin(e["coinbase_value"]), e["ntx"], e["version"], extra))
            elif e.get("kind") == "state":
                facts = ", ".join("%s: %s" % (k.replace("_", " "), v) for k, v in e.items() if k not in ("scenario", "step", "kind", "note", "tip", "validator"))
                w("| %s | %s | | | | %s |" % (e["step"], e.get("validator", ""), facts))
        w("")

    w("## Manipulated blocks at the transition height\n")
    w("Hand-built empty blocks (not from any implementation's miner), offered to all three on top of the same")
    w("block 839.\n")
    w("| Block | C | A | L |")
    w("|---|---|---|---|")
    rows = {}
    for e in rec:
        if e["scenario"] == "negative":
            rows.setdefault(e["step"].split(": ", 1)[1], {})[e["validator"]] = verdict(e)
    for name, d in rows.items():
        w("| %s | %s | %s | %s |" % (name, d.get("C", ""), d.get("A", ""), d.get("L", "")))
    w("")

    w("## Peer connections\n")
    w("Manual outbound connections (`addnode <peer> onetry`), checked four seconds later.\n")
    w("| When | From → to | Connection kept | Services the peer announced |")
    w("|---|---|---|---|")
    for e in rec:
        if e.get("kind") == "p2p":
            when = "below the transition height" if "below" in e["step"] else "above the transition height"
            services = ", ".join(e["peer"]["services"]) if e.get("peer") else ""
            w("| %s | %s → %s | %s | %s |" % (when, e["source"], e["target"], "yes" if e["kept"] else "**no**", services))
    w("")
    open(sys.argv[2], "w", encoding="utf8").write("\n".join(out))


if __name__ == "__main__":
    main()
