#!/usr/bin/env python3
"""Derive stable empirical security-economics review artifacts offline.

This script reads one frozen node/API snapshot selected by the machine-readable
configuration. It performs no network or RPC calls, so document regeneration
cannot silently change the evidence base.
"""

from __future__ import annotations

import csv
import gzip
import hashlib
import json
import math
import statistics
import textwrap
from collections import defaultdict, deque
from datetime import datetime, timezone
from decimal import Decimal, getcontext
from pathlib import Path
from typing import Any, Iterable

from PIL import Image, ImageDraw, ImageFont

import simulate_monetary_scenarios as monetary


getcontext().prec = 80
REVISION = ""
D = Decimal
COIN = D(100_000_000)
HASHRATE_ROLLING_BLOCKS = 120
COLORS = {
    "blue": (0, 126, 167),
    "cyan": (0, 177, 210),
    "orange": (224, 111, 27),
    "red": (176, 44, 44),
    "green": (42, 133, 92),
    "gray": (95, 105, 112),
}


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"), parse_float=Decimal)


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    if not rows:
        raise ValueError(f"Refusing to write empty CSV: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=list(rows[0]),
            lineterminator="\n",
        )
        writer.writeheader()
        writer.writerows(rows)


def iso_utc(unix_time: int) -> str:
    return (
        datetime.fromtimestamp(unix_time, timezone.utc)
        .isoformat(timespec="seconds")
        .replace("+00:00", "Z")
    )


def fmt_decimal(value: Decimal | float | int, places: int = 8) -> str:
    decimal = D(str(value))
    return f"{decimal.quantize(D(1).scaleb(-places)):f}"


def fmt_compact(value: Decimal | float | int, places: int = 4) -> str:
    decimal = D(str(value))
    return f"{decimal.quantize(D(1).scaleb(-places)):f}"


def percentile(values: list[float | int], fraction: float) -> float:
    if not values:
        raise ValueError("Cannot calculate percentile of an empty sequence")
    ordered = sorted(values)
    position = (len(ordered) - 1) * fraction
    lower = math.floor(position)
    upper = math.ceil(position)
    if lower == upper:
        return float(ordered[lower])
    weight = position - lower
    return float(ordered[lower]) * (1 - weight) + float(ordered[upper]) * weight


def stats(values: list[float | int]) -> dict[str, float]:
    if not values:
        return {name: math.nan for name in ("mean", "median", "minimum", "maximum", "p10", "p90")}
    return {
        "mean": statistics.fmean(values),
        "median": statistics.median(values),
        "minimum": float(min(values)),
        "maximum": float(max(values)),
        "p10": percentile(values, 0.10),
        "p90": percentile(values, 0.90),
    }


def generated_header(source: str) -> str:
    return (
        "<!-- Generated by scripts/analyze_empirical_snapshot.py "
        f"from {source}. Do not edit by hand. -->\n\n"
    )


def md_table(
    headers: list[str],
    rows: list[list[str]],
    alignments: list[str],
    column_relative_widths: list[int] | None = None,
) -> str:
    markers = {"left": ":---", "center": ":---:", "right": "---:"}
    if len(headers) != len(alignments):
        raise ValueError("Markdown header/alignment length mismatch")
    if column_relative_widths is not None:
        if any(
            isinstance(width, bool) or not isinstance(width, int) or width <= 0
            for width in column_relative_widths
        ):
            raise ValueError("Markdown table column widths must be positive integers")
    for row in rows:
        if len(row) != len(headers):
            raise ValueError("Markdown table row length mismatch")
    lines = [
        "| " + " | ".join(headers) + " |",
        "|" + "|".join(markers[item] for item in alignments) + "|",
    ]
    lines.extend("| " + " | ".join(row) + " |" for row in rows)
    table = "\n".join(lines) + "\n"
    if column_relative_widths is None:
        return table
    widths = ",".join(str(width) for width in column_relative_widths)
    return table + f'\n: {{tbl-colwidths="[{widths}]"}}\n'


def write_include(
    root: Path,
    name: str,
    source: str,
    headers: list[str],
    rows: list[list[str]],
    alignments: list[str],
    column_relative_widths: list[int] | None = None,
) -> None:
    path = root / "includes" / name
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        generated_header(source)
        + md_table(
            headers,
            rows,
            alignments,
            column_relative_widths=column_relative_widths,
        ),
        encoding="utf-8",
    )


def source_entry(manifest: dict[str, Any], filename: str) -> dict[str, Any]:
    matches = [
        item for item in manifest["files"] if str(item["path"]).endswith("/" + filename)
    ]
    if len(matches) != 1:
        raise ValueError(f"Expected one manifest entry for {filename}, found {len(matches)}")
    return matches[0]


def verify_frozen_sources(root: Path, manifest: dict[str, Any]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for item in manifest["files"]:
        path = root / item["path"]
        actual = sha256(path)
        if actual != item["sha256"]:
            raise ValueError(f"Frozen source hash mismatch: {path}")
        rows.append(
            {
                "path": item["path"],
                "source_url": item["source_url"],
                "retrieved_utc": item["retrieved_utc"],
                "sha256": actual,
                "bytes": item["bytes"],
                "http_status": item["http_status"],
                "evidence_class": "frozen source response",
            }
        )
    return rows


def block_history(
    root: Path,
    snapshot_dir: Path,
    config: dict[str, Any],
) -> tuple[dict[int, dict[str, Any]], dict[int, int], list[dict[str, Any]], list[dict[str, Any]]]:
    empirical = config["empirical_security"]
    windows = [int(value) for value in empirical["history_windows_days"]]
    tip = read_json(snapshot_dir / "node_tip_block.json")
    tip_time = int(tip["header"]["time"])
    cutoffs = {days: tip_time - days * 86400 for days in windows}
    rolling_blocks = int(empirical["rolling_hashrate_window_blocks"])

    accumulators: dict[int, dict[str, Any]] = {}
    for days in windows:
        accumulators[days] = {
            "difficulty": [],
            "hashrate_hps": [],
            "block_interval_seconds": [],
            "non_coinbase_transactions": [],
            "total_fees_base_units": [],
            "fee_share_pct": [],
            "total_subsidy_base_units": 0,
            "total_fees_sum_base_units": 0,
            "zero_transaction_blocks": 0,
            "first_time": None,
            "last_time": None,
            "blocks": 0,
        }

    history_path = snapshot_dir / "node_block_history_365d.jsonl.gz"
    hashrate_path = root / "data" / f"{REVISION}hashrate_history.csv.gz"
    fee_path = root / "data" / f"{REVISION}fee_per_block_history.csv.gz"
    hashrate_path.parent.mkdir(parents=True, exist_ok=True)

    rolling: deque[tuple[int, int, int]] = deque()
    previous_time: int | None = None
    transaction_block_times: dict[int, int] = {}
    daily_hashrates: dict[str, list[float]] = defaultdict(list)
    daily_fees: dict[str, list[int]] = defaultdict(list)

    with (
        gzip.open(history_path, "rt", encoding="utf-8") as source,
        gzip.open(hashrate_path, "wt", newline="", encoding="utf-8") as hash_output,
        gzip.open(fee_path, "wt", newline="", encoding="utf-8") as fee_output,
    ):
        hash_writer = csv.DictWriter(
            hash_output,
            fieldnames=[
                "height",
                "time_utc",
                "difficulty",
                "block_interval_seconds",
                f"rolling_{rolling_blocks}_block_hashrate_hps",
                f"rolling_{rolling_blocks}_block_hashrate_mhps",
            ],
            lineterminator="\n",
        )
        fee_writer = csv.DictWriter(
            fee_output,
            fieldnames=[
                "height",
                "time_utc",
                "subsidy_base_units",
                "total_fees_base_units",
                "total_fees_rin",
                "non_coinbase_transactions",
                "fee_share_of_miner_revenue_pct",
            ],
            lineterminator="\n",
        )
        hash_writer.writeheader()
        fee_writer.writeheader()

        for line in source:
            record = json.loads(line)
            height = int(record["height"])
            block_time = int(record["time"])
            chainwork = int(record["chainwork"], 16)
            difficulty = float(record["difficulty"])
            subsidy = int(record["subsidy_base_units"])
            total_fees = int(record["total_fees_base_units"])
            transaction_count = int(record["non_coinbase_transactions"])
            interval = block_time - previous_time if previous_time is not None else None
            previous_time = block_time

            rolling.append((height, block_time, chainwork))
            if len(rolling) > rolling_blocks + 1:
                rolling.popleft()
            rolling_hashrate: float | None = None
            if len(rolling) == rolling_blocks + 1:
                elapsed = block_time - rolling[0][1]
                work = chainwork - rolling[0][2]
                if elapsed > 0 and work > 0:
                    rolling_hashrate = work / elapsed

            timestamp = iso_utc(block_time)
            fee_share = (
                D(total_fees) * D(100) / D(subsidy + total_fees)
                if subsidy + total_fees
                else D(0)
            )
            hash_writer.writerow(
                {
                    "height": height,
                    "time_utc": timestamp,
                    "difficulty": fmt_decimal(difficulty, 12),
                    "block_interval_seconds": "" if interval is None else interval,
                    f"rolling_{rolling_blocks}_block_hashrate_hps": (
                        "" if rolling_hashrate is None else fmt_decimal(rolling_hashrate, 4)
                    ),
                    f"rolling_{rolling_blocks}_block_hashrate_mhps": (
                        "" if rolling_hashrate is None else fmt_decimal(rolling_hashrate / 1_000_000, 8)
                    ),
                }
            )
            fee_writer.writerow(
                {
                    "height": height,
                    "time_utc": timestamp,
                    "subsidy_base_units": subsidy,
                    "total_fees_base_units": total_fees,
                    "total_fees_rin": fmt_decimal(D(total_fees) / COIN),
                    "non_coinbase_transactions": transaction_count,
                    "fee_share_of_miner_revenue_pct": fmt_decimal(fee_share, 12),
                }
            )

            day = timestamp[:10]
            if rolling_hashrate is not None:
                daily_hashrates[day].append(rolling_hashrate)
            daily_fees[day].append(total_fees)
            if transaction_count:
                transaction_block_times[height] = block_time

            for days, cutoff in cutoffs.items():
                if block_time < cutoff:
                    continue
                accumulator = accumulators[days]
                accumulator["blocks"] += 1
                accumulator["first_time"] = (
                    block_time
                    if accumulator["first_time"] is None
                    else min(accumulator["first_time"], block_time)
                )
                accumulator["last_time"] = (
                    block_time
                    if accumulator["last_time"] is None
                    else max(accumulator["last_time"], block_time)
                )
                accumulator["difficulty"].append(difficulty)
                if rolling_hashrate is not None:
                    accumulator["hashrate_hps"].append(rolling_hashrate)
                if interval is not None:
                    accumulator["block_interval_seconds"].append(interval)
                accumulator["non_coinbase_transactions"].append(transaction_count)
                accumulator["total_fees_base_units"].append(total_fees)
                accumulator["fee_share_pct"].append(float(fee_share))
                accumulator["total_subsidy_base_units"] += subsidy
                accumulator["total_fees_sum_base_units"] += total_fees
                if transaction_count == 0:
                    accumulator["zero_transaction_blocks"] += 1

    daily_hash_rows = [
        {
            "date_utc": day,
            "mean_rolling_hashrate_hps": fmt_decimal(statistics.fmean(values), 4),
            "mean_rolling_hashrate_mhps": fmt_decimal(statistics.fmean(values) / 1_000_000, 8),
            "observations": len(values),
        }
        for day, values in sorted(daily_hashrates.items())
    ]
    daily_fee_rows = [
        {
            "date_utc": day,
            "mean_total_fee_base_units_per_block": fmt_decimal(statistics.fmean(values), 4),
            "median_total_fee_base_units_per_block": fmt_decimal(statistics.median(values), 4),
            "mean_total_fee_rin_per_block": fmt_decimal(D(str(statistics.fmean(values))) / COIN),
            "blocks": len(values),
        }
        for day, values in sorted(daily_fees.items())
    ]
    write_csv(root / "data" / f"{REVISION}daily_hashrate_history.csv", daily_hash_rows)
    write_csv(root / "data" / f"{REVISION}daily_fee_history.csv", daily_fee_rows)
    return accumulators, transaction_block_times, daily_hash_rows, daily_fee_rows


def exact_transaction_fees(
    snapshot_dir: Path,
    transaction_block_times: dict[int, int],
    tip_time: int,
    windows: list[int],
) -> tuple[dict[int, list[int]], int]:
    fees_by_window = {days: [] for days in windows}
    total = 0
    path = snapshot_dir / "node_transaction_fees_365d.jsonl.gz"
    with gzip.open(path, "rt", encoding="utf-8") as handle:
        for line in handle:
            record = json.loads(line)
            height = int(record["height"])
            block_time = transaction_block_times[height]
            fee = int(record["fee_base_units"])
            total += fee
            for days in windows:
                if block_time >= tip_time - days * 86400:
                    fees_by_window[days].append(fee)
    return fees_by_window, total


def orphan_baseline(
    root: Path,
    snapshot_dir: Path,
    tip_time: int,
    windows: list[int],
) -> dict[int, dict[str, Any]]:
    path = snapshot_dir / "explorer_last_orphans_365d.jsonl.gz"
    records: list[dict[str, Any]] = []
    with gzip.open(path, "rt", encoding="utf-8") as handle:
        for line in handle:
            records.append(json.loads(line))
    write_csv(
        root / "data" / f"{REVISION}orphan_history.csv",
        [
            {
                "block_index": item["blockindex"],
                "block_hash": item["blockhash"],
                "previous_block_hash": item["prev_blockhash"],
                "reorg_depth": item["reorg_depth"],
                "transaction_count": item["tx_count"],
                "amount_rin": item["amount"],
                "timestamp_unix": item["timestamp"],
                "timestamp_utc": iso_utc(int(item["timestamp"])),
                "evidence_class": "directly observed explorer orphan index",
            }
            for item in records
        ],
    )
    summaries: dict[int, dict[str, Any]] = {}
    for days in windows:
        selected = [
            item
            for item in records
            if int(item["timestamp"]) >= tip_time - days * 86400
        ]
        depths = [int(item["reorg_depth"]) for item in selected]
        summaries[days] = {
            "count": len(selected),
            "depth": stats(depths) if depths else None,
            "coverage_status": (
                "complete for the explorer's returned orphan index; endpoint "
                "exhausted below its 100-record page limit, but index retention "
                "and pre-index history were not independently verified"
            ),
        }
    write_csv(
        root / "data" / f"{REVISION}orphan_baseline.csv",
        [
            {
                "window_days": days,
                "indexed_orphaned_blocks": summary["count"],
                "reorg_depth_mean": (
                    fmt_decimal(summary["depth"]["mean"], 4)
                    if summary["depth"] is not None
                    else ""
                ),
                "reorg_depth_median": (
                    fmt_decimal(summary["depth"]["median"], 4)
                    if summary["depth"] is not None
                    else ""
                ),
                "reorg_depth_p90": (
                    fmt_decimal(summary["depth"]["p90"], 4)
                    if summary["depth"] is not None
                    else ""
                ),
                "reorg_depth_maximum": (
                    fmt_decimal(summary["depth"]["maximum"], 4)
                    if summary["depth"] is not None
                    else ""
                ),
                "coverage_status": summary["coverage_status"],
                "evidence_class": "directly observed explorer orphan index",
            }
            for days, summary in sorted(summaries.items())
        ],
    )
    return summaries


def export_historical_baseline(
    root: Path,
    snapshot_dir: Path,
    config: dict[str, Any],
    accumulators: dict[int, dict[str, Any]],
    transaction_fees: dict[int, list[int]],
    orphan_summaries: dict[int, dict[str, Any]],
) -> tuple[list[dict[str, Any]], dict[int, dict[str, Any]]]:
    rows: list[dict[str, Any]] = []
    summaries: dict[int, dict[str, Any]] = {}
    for days in sorted(accumulators):
        acc = accumulators[days]
        difficulty = stats(acc["difficulty"])
        hashrate = stats(acc["hashrate_hps"])
        intervals = stats(acc["block_interval_seconds"])
        transactions = stats(acc["non_coinbase_transactions"])
        block_fees = stats(acc["total_fees_base_units"])
        active_block_fees = stats(
            [value for value in acc["total_fees_base_units"] if value > 0]
        )
        tx_fees = stats(transaction_fees[days])
        span_days = (acc["last_time"] - acc["first_time"]) / 86400
        actual_blocks_per_day = (acc["blocks"] - 1) / span_days if span_days > 0 else math.nan
        aggregate_fee_share = (
            D(acc["total_fees_sum_base_units"])
            * D(100)
            / D(acc["total_subsidy_base_units"] + acc["total_fees_sum_base_units"])
        )
        summary = {
            "window_days": days,
            "start_utc": iso_utc(acc["first_time"]),
            "end_utc": iso_utc(acc["last_time"]),
            "block_count": acc["blocks"],
            "actual_span_days": span_days,
            "actual_blocks_per_day": actual_blocks_per_day,
            "difficulty": difficulty,
            "hashrate": hashrate,
            "intervals": intervals,
            "transactions": transactions,
            "block_fees": block_fees,
            "active_block_fees": active_block_fees,
            "tx_fees": tx_fees,
            "non_coinbase_transaction_count": len(transaction_fees[days]),
            "zero_transaction_blocks_pct": (
                acc["zero_transaction_blocks"] * 100 / acc["blocks"]
            ),
            "aggregate_fee_share_pct": float(aggregate_fee_share),
            "mean_fee_per_transaction_base_units": (
                acc["total_fees_sum_base_units"] / len(transaction_fees[days])
                if transaction_fees[days]
                else 0
            ),
            "indexed_orphaned_blocks": orphan_summaries[days]["count"],
            "indexed_orphan_depth": orphan_summaries[days]["depth"],
            "orphan_coverage_status": orphan_summaries[days]["coverage_status"],
        }
        summaries[days] = summary
        rows.append(
            {
                "window_days": days,
                "start_utc": summary["start_utc"],
                "end_utc": summary["end_utc"],
                "block_count": summary["block_count"],
                "actual_blocks_per_day": fmt_decimal(actual_blocks_per_day, 4),
                "network_hashrate_mean_mhps": fmt_decimal(hashrate["mean"] / 1_000_000, 8),
                "network_hashrate_median_mhps": fmt_decimal(hashrate["median"] / 1_000_000, 8),
                "network_hashrate_minimum_mhps": fmt_decimal(hashrate["minimum"] / 1_000_000, 8),
                "network_hashrate_maximum_mhps": fmt_decimal(hashrate["maximum"] / 1_000_000, 8),
                "network_hashrate_p10_mhps": fmt_decimal(hashrate["p10"] / 1_000_000, 8),
                "network_hashrate_p90_mhps": fmt_decimal(hashrate["p90"] / 1_000_000, 8),
                "difficulty_mean": fmt_decimal(difficulty["mean"], 12),
                "difficulty_median": fmt_decimal(difficulty["median"], 12),
                "difficulty_minimum": fmt_decimal(difficulty["minimum"], 12),
                "difficulty_maximum": fmt_decimal(difficulty["maximum"], 12),
                "difficulty_p10": fmt_decimal(difficulty["p10"], 12),
                "difficulty_p90": fmt_decimal(difficulty["p90"], 12),
                "block_interval_mean_seconds": fmt_decimal(intervals["mean"], 4),
                "block_interval_median_seconds": fmt_decimal(intervals["median"], 4),
                "block_interval_minimum_seconds": fmt_decimal(intervals["minimum"], 4),
                "block_interval_maximum_seconds": fmt_decimal(intervals["maximum"], 4),
                "block_interval_p10_seconds": fmt_decimal(intervals["p10"], 4),
                "block_interval_p90_seconds": fmt_decimal(intervals["p90"], 4),
                "non_coinbase_transactions": summary["non_coinbase_transaction_count"],
                "transactions_per_block_mean": fmt_decimal(transactions["mean"], 8),
                "transactions_per_block_median": fmt_decimal(transactions["median"], 8),
                "transactions_per_block_p10": fmt_decimal(transactions["p10"], 8),
                "transactions_per_block_p90": fmt_decimal(transactions["p90"], 8),
                "zero_non_coinbase_transaction_blocks_pct": fmt_decimal(
                    summary["zero_transaction_blocks_pct"], 8
                ),
                "total_fee_per_block_mean_base_units": fmt_decimal(block_fees["mean"], 4),
                "total_fee_per_block_median_base_units": fmt_decimal(block_fees["median"], 4),
                "total_fee_per_block_p10_base_units": fmt_decimal(block_fees["p10"], 4),
                "total_fee_per_block_p90_base_units": fmt_decimal(block_fees["p90"], 4),
                "mean_fee_per_non_coinbase_transaction_base_units": fmt_decimal(
                    summary["mean_fee_per_transaction_base_units"], 4
                ),
                "median_fee_per_non_coinbase_transaction_base_units": fmt_decimal(
                    tx_fees["median"], 4
                ),
                "fee_per_non_coinbase_transaction_p10_base_units": fmt_decimal(
                    tx_fees["p10"], 4
                ),
                "fee_per_non_coinbase_transaction_p90_base_units": fmt_decimal(
                    tx_fees["p90"], 4
                ),
                "aggregate_fee_share_of_miner_revenue_pct": fmt_decimal(
                    aggregate_fee_share, 12
                ),
                "indexed_orphaned_block_count": summary["indexed_orphaned_blocks"],
                "indexed_orphan_rate_pct": fmt_decimal(
                    D(summary["indexed_orphaned_blocks"])
                    * D(100)
                    / D(summary["block_count"] + summary["indexed_orphaned_blocks"]),
                    8,
                ),
                "indexed_orphan_reorg_depth_p90": (
                    fmt_decimal(summary["indexed_orphan_depth"]["p90"], 4)
                    if summary["indexed_orphan_depth"] is not None
                    else ""
                ),
                "indexed_orphan_reorg_depth_maximum": (
                    fmt_decimal(summary["indexed_orphan_depth"]["maximum"], 4)
                    if summary["indexed_orphan_depth"] is not None
                    else ""
                ),
                "orphan_evidence_status": summary["orphan_coverage_status"],
                "evidence_class": "derived from observed local-node chain data",
            }
        )
    write_csv(root / "data" / f"{REVISION}historical_network_baseline.csv", rows)

    metrics = [
        (
            "Blocks observed",
            lambda s: f"{s['block_count']:,}",
            "blocks",
        ),
        (
            "Actual blocks/day",
            lambda s: fmt_compact(s["actual_blocks_per_day"], 2),
            "blocks/day",
        ),
        (
            "Rolling hashrate, median",
            lambda s: fmt_compact(s["hashrate"]["median"] / 1_000_000, 3),
            "MH/s",
        ),
        (
            "Rolling hashrate, p10-p90",
            lambda s: (
                f"{fmt_compact(s['hashrate']['p10'] / 1_000_000, 3)}-"
                f"{fmt_compact(s['hashrate']['p90'] / 1_000_000, 3)}"
            ),
            "MH/s",
        ),
        (
            "Difficulty, median",
            lambda s: fmt_compact(s["difficulty"]["median"], 6),
            "difficulty",
        ),
        (
            "Block interval, median",
            lambda s: fmt_compact(s["intervals"]["median"], 1),
            "seconds",
        ),
        (
            "Block interval, p10-p90",
            lambda s: (
                f"{fmt_compact(s['intervals']['p10'], 1)}-"
                f"{fmt_compact(s['intervals']['p90'], 1)}"
            ),
            "seconds",
        ),
        (
            "Non-coinbase transactions",
            lambda s: f"{s['non_coinbase_transaction_count']:,}",
            "transactions",
        ),
        (
            "Blocks with no non-coinbase transaction",
            lambda s: fmt_compact(s["zero_transaction_blocks_pct"], 2),
            "%",
        ),
        (
            "Total fee/block, mean",
            lambda s: fmt_decimal(D(str(s["block_fees"]["mean"])) / COIN),
            "RIN/block",
        ),
        (
            "Total fee/block, median",
            lambda s: fmt_decimal(D(str(s["block_fees"]["median"])) / COIN),
            "RIN/block",
        ),
        (
            "Fee/non-coinbase transaction, mean",
            lambda s: fmt_decimal(
                D(str(s["mean_fee_per_transaction_base_units"])) / COIN
            ),
            "RIN/transaction",
        ),
        (
            "Fee/non-coinbase transaction, median",
            lambda s: fmt_decimal(D(str(s["tx_fees"]["median"])) / COIN),
            "RIN/transaction",
        ),
        (
            "Aggregate fee share of miner revenue",
            lambda s: fmt_decimal(s["aggregate_fee_share_pct"], 6),
            "%",
        ),
        (
            "Indexed orphaned blocks",
            lambda s: str(s["indexed_orphaned_blocks"]),
            "blocks",
        ),
        (
            "Indexed orphan incidence",
            lambda s: fmt_decimal(
                D(s["indexed_orphaned_blocks"])
                * D(100)
                / D(s["block_count"] + s["indexed_orphaned_blocks"]),
                6,
            ),
            "%",
        ),
        (
            "Indexed orphan reorg depth, maximum",
            lambda s: (
                fmt_compact(s["indexed_orphan_depth"]["maximum"], 0)
                if s["indexed_orphan_depth"] is not None
                else "n/a"
            ),
            "blocks",
        ),
    ]
    include_rows = [
        [
            label,
            *(formatter(summaries[days]) for days in sorted(summaries)),
            unit,
        ]
        for label, formatter, unit in metrics
    ]
    write_include(
        root,
        f"{REVISION}historical_network_baseline_table.qmd",
        f"data/{REVISION}historical_network_baseline.csv",
        ["Metric", "30 days", "90 days", "365 days", "Unit"],
        include_rows,
        ["left", "right", "right", "right", "left"],
        column_relative_widths=[37, 14, 14, 14, 21],
    )
    return rows, summaries


def hashrate_to_mh(value: Any, unit: str) -> Decimal:
    number = D(str(value or 0))
    normalized = unit.lower()
    if normalized == "mh":
        return number
    if normalized == "kh":
        return number / D(1000)
    if normalized in {"hash", "h"}:
        return number / D(1_000_000)
    raise ValueError(f"Unsupported hashrate unit: {unit}")


def parse_rental_market(
    root: Path,
    snapshot_dir: Path,
    config: dict[str, Any],
    current_hashrate_mh: Decimal,
    btc_usd: Decimal,
) -> tuple[dict[str, Any], list[dict[str, Any]], list[dict[str, Any]]]:
    payload = read_json(snapshot_dir / "mrr_rinhash_rigs.json")
    records = payload["data"]["records"]
    listing_rows: list[dict[str, Any]] = []
    priced_rigs: list[dict[str, Any]] = []
    for item in records:
        advertised = hashrate_to_mh(
            item["hashrate"]["advertised"]["hash"],
            item["hashrate"]["advertised"]["type"],
        )
        last_5 = hashrate_to_mh(
            item["hashrate"]["last_5min"]["hash"],
            item["hashrate"]["last_5min"]["type"],
        )
        btc = item["price"]["BTC"]
        ask = D(str(btc["price"]))
        min_hours = D(str(item["minhours"]))
        max_hours = D(str(item["maxhours"]))
        daily_cost = advertised * ask
        minimum_contract_cost = daily_cost * min_hours / D(24)
        rig = {
            "id": item["id"],
            "name": item["name"],
            "advertised_mh": advertised,
            "last_5min_mh": last_5,
            "ask_btc_per_mh_day": ask,
            "daily_cost_btc": daily_cost,
            "minimum_contract_cost_btc": minimum_contract_cost,
            "minimum_hours": min_hours,
            "maximum_hours": max_hours,
        }
        priced_rigs.append(rig)
        listing_rows.append(
            {
                "rig_id": item["id"],
                "name": item["name"],
                "owner": item["owner"],
                "status": item["status"]["status"],
                "online": str(bool(item["online"])).lower(),
                "rented": str(bool(item["status"]["rented"])).lower(),
                "pool_status": item["poolstatus"],
                "xnonce": item["xnonce"],
                "location": item["region"],
                "advertised_hashrate_mhps": fmt_decimal(advertised, 6),
                "observed_last_5min_hashrate_mhps": fmt_decimal(last_5, 6),
                "price_unit": "BTC/MH/day",
                "ask_btc_per_mh_day": fmt_decimal(ask, 12),
                "minimum_rental_hours": fmt_decimal(min_hours, 2),
                "minimum_contractual_price_btc": fmt_decimal(
                    minimum_contract_cost, 12
                ),
                "minimum_contractual_price_usd": fmt_decimal(
                    minimum_contract_cost * btc_usd, 6
                ),
                "maximum_rental_hours": fmt_decimal(max_hours, 2),
                "rental_history": "not exposed per listing in frozen API response",
                "evidence_class": "directly observed ask listing; delivery unverified",
            }
        )
    write_csv(root / "data" / f"{REVISION}rental_market_listings.csv", listing_rows)

    available = [
        rig
        for rig, item in zip(priced_rigs, records)
        if item["status"]["status"] == "available" and bool(item["online"])
    ]
    available.sort(key=lambda item: (item["ask_btc_per_mh_day"], item["id"]))
    total_advertised = sum((item["advertised_mh"] for item in available), D(0))
    total_last_5 = sum((item["last_5min_mh"] for item in available), D(0))
    weighted_ask = (
        sum((item["daily_cost_btc"] for item in available), D(0)) / total_advertised
        if total_advertised
        else D(0)
    )
    total_daily_cost = sum(
        (item["daily_cost_btc"] for item in available), D(0)
    )
    total_minimum_contract_cost = sum(
        (item["minimum_contract_cost_btc"] for item in available), D(0)
    )
    api_available = hashrate_to_mh(
        payload["data"]["stats"]["available"]["hash"]["hash"],
        payload["data"]["stats"]["available"]["hash"]["type"],
    )
    if abs(total_advertised - api_available) > D("0.000001"):
        raise ValueError("MRR listing capacity does not match API aggregate")

    horizons = [int(value) for value in config["empirical_security"]["rental_horizons_blocks"]]
    curve_rows: list[dict[str, Any]] = []
    cumulative_hash = D(0)
    cumulative_daily = D(0)
    cumulative_minimum = D(0)
    cumulative_theoretical = {blocks: D(0) for blocks in horizons}
    cumulative_contract = {blocks: D(0) for blocks in horizons}
    for rank, rig in enumerate(available, 1):
        cumulative_hash += rig["advertised_mh"]
        cumulative_daily += rig["daily_cost_btc"]
        minimum_cost = rig["daily_cost_btc"] * rig["minimum_hours"] / D(24)
        cumulative_minimum += minimum_cost
        row: dict[str, Any] = {
            "rank_by_ask": rank,
            "rig_id": rig["id"],
            "advertised_hashrate_mhps": fmt_decimal(rig["advertised_mh"], 6),
            "ask_btc_per_mh_day": fmt_decimal(rig["ask_btc_per_mh_day"], 12),
            "cumulative_hashrate_mhps": fmt_decimal(cumulative_hash, 6),
            "cumulative_daily_cost_btc": fmt_decimal(cumulative_daily, 12),
            "cumulative_daily_cost_usd": fmt_decimal(cumulative_daily * btc_usd, 6),
            "cumulative_minimum_contract_cost_btc": fmt_decimal(cumulative_minimum, 12),
            "cumulative_minimum_contract_cost_usd": fmt_decimal(
                cumulative_minimum * btc_usd, 6
            ),
        }
        for blocks in horizons:
            hours = D(blocks) / D(60)
            theoretical = rig["daily_cost_btc"] * hours / D(24)
            contract = (
                rig["daily_cost_btc"]
                * max(hours, rig["minimum_hours"])
                / D(24)
            )
            cumulative_theoretical[blocks] += theoretical
            cumulative_contract[blocks] += contract
            row[f"cumulative_theoretical_{blocks}_block_cost_btc"] = fmt_decimal(
                cumulative_theoretical[blocks], 12
            )
            row[f"cumulative_actual_minimum_{blocks}_block_cost_btc"] = fmt_decimal(
                cumulative_contract[blocks], 12
            )
        curve_rows.append(row)
    write_csv(root / "data" / f"{REVISION}rental_cost_curve.csv", curve_rows)

    market_html = (snapshot_dir / "mrr_rinhash_market.html").read_text(
        encoding="utf-8", errors="replace"
    )
    compact_market_html = " ".join(market_html.split())
    no_recent_rentals = (
        "30 Day Rentals" in compact_market_html
        and "No rentals in 30d" in compact_market_html
    )
    summary = {
        "listed_rigs": len(records),
        "available_online_rigs": len(available),
        "advertised_available_mh": total_advertised,
        "observed_last_5min_mh": total_last_5,
        "lowest_ask_btc_per_mh_day": min(
            (item["ask_btc_per_mh_day"] for item in available), default=D(0)
        ),
        "highest_ask_btc_per_mh_day": max(
            (item["ask_btc_per_mh_day"] for item in available), default=D(0)
        ),
        "weighted_ask_btc_per_mh_day": weighted_ask,
        "all_capacity_24h_cost_btc": total_daily_cost,
        "all_capacity_minimum_contract_cost_btc": total_minimum_contract_cost,
        "capacity_pct_honest": (
            total_advertised * D(100) / current_hashrate_mh
            if current_hashrate_mh
            else D(0)
        ),
        "capacity_pct_combined": (
            total_advertised * D(100) / (current_hashrate_mh + total_advertised)
            if current_hashrate_mh + total_advertised
            else D(0)
        ),
        "no_recent_rentals_reported": no_recent_rentals,
        "btc_usd": btc_usd,
    }

    cost_summary_rows: list[dict[str, Any]] = []
    final = curve_rows[-1]
    for blocks in horizons:
        cost_summary_rows.append(
            {
                "rental_scope": "all visible available advertised capacity",
                "analytical_horizon_blocks": blocks,
                "analytical_horizon_hours": fmt_decimal(D(blocks) / D(60), 4),
                "theoretical_prorated_cost_btc": final[
                    f"cumulative_theoretical_{blocks}_block_cost_btc"
                ],
                "theoretical_prorated_cost_usd": fmt_decimal(
                    D(final[f"cumulative_theoretical_{blocks}_block_cost_btc"])
                    * btc_usd,
                    6,
                ),
                "actual_minimum_lease_cost_btc": final[
                    f"cumulative_actual_minimum_{blocks}_block_cost_btc"
                ],
                "actual_minimum_lease_cost_usd": fmt_decimal(
                    D(final[f"cumulative_actual_minimum_{blocks}_block_cost_btc"])
                    * btc_usd,
                    6,
                ),
                "evidence_class": (
                    "derived from quoted asks and contractual minimum durations; "
                    "not an executed rental price"
                ),
            }
        )
    write_csv(root / "data" / f"{REVISION}rental_cost_horizons.csv", cost_summary_rows)

    minimum_below_24 = sum(item["minimum_hours"] < D(24) for item in available)
    minimum_equal_24 = sum(item["minimum_hours"] == D(24) for item in available)
    minimum_above_24 = sum(item["minimum_hours"] > D(24) for item in available)
    reconciliation_rows = [
        {
            "metric": "advertised available capacity",
            "value": fmt_decimal(total_advertised, 6),
            "unit": "MH/s",
            "calculation": "sum of advertised hashrate across available API-online listings",
        },
        {
            "metric": "capacity-weighted ask",
            "value": fmt_decimal(weighted_ask, 12),
            "unit": "BTC/MH/day",
            "calculation": "sum(listing hashrate * ask) / sum(listing hashrate)",
        },
        {
            "metric": "all-capacity weighted 24-hour price",
            "value": fmt_decimal(total_daily_cost, 12),
            "unit": "BTC",
            "calculation": "sum(listing hashrate * ask * 24/24)",
        },
        {
            "metric": "sum of listing minimum contractual prices",
            "value": fmt_decimal(total_minimum_contract_cost, 12),
            "unit": "BTC",
            "calculation": "sum(listing hashrate * ask * listing minimum hours / 24)",
        },
        {
            "metric": "minimum-price share of 24-hour price",
            "value": fmt_decimal(
                total_minimum_contract_cost * D(100) / total_daily_cost, 6
            ),
            "unit": "%",
            "calculation": "sum of listing minimum prices / all-capacity 24-hour price",
        },
        {
            "metric": "listings with minimum below / equal to / above 24 hours",
            "value": f"{minimum_below_24} / {minimum_equal_24} / {minimum_above_24}",
            "unit": "listings",
            "calculation": "direct classification of listing minimum-duration fields",
        },
    ]
    write_csv(
        root / "data" / f"{REVISION}rental_cost_reconciliation.csv",
        reconciliation_rows,
    )

    write_include(
        root,
        f"{REVISION}rental_market_summary_table.qmd",
        f"data/{REVISION}rental_market_listings.csv",
        ["Metric", "Value", "Unit", "Evidence status"],
        [
            ["Visible listed rigs", str(summary["listed_rigs"]), "rigs", "directly observed"],
            [
                "Available and API-online rigs",
                str(summary["available_online_rigs"]),
                "rigs",
                "directly observed status",
            ],
            [
                "Advertised available capacity",
                fmt_decimal(total_advertised, 6),
                "MH/s",
                "quoted capacity; delivery unverified",
            ],
            [
                "Observed five-minute delivered rate",
                fmt_decimal(total_last_5, 6),
                "MH/s",
                "API sample; idle-on-rent rigs may report zero",
            ],
            [
                "Lowest ask",
                fmt_decimal(summary["lowest_ask_btc_per_mh_day"], 8),
                "BTC/MH/day",
                "quoted ask, not market-clearing price",
            ],
            [
                "Capacity / observed honest hashrate",
                fmt_decimal(summary["capacity_pct_honest"], 2),
                "%",
                "derived from frozen snapshots",
            ],
            [
                "Capacity / combined hashrate",
                fmt_decimal(summary["capacity_pct_combined"], 2),
                "%",
                "derived from frozen snapshots",
            ],
            [
                "Recent executed rentals",
                "none reported in 30-day market panel" if no_recent_rentals else "not established",
                "",
                "ask prices are not market-clearing evidence",
            ],
        ],
        ["left", "right", "left", "left"],
        column_relative_widths=[30, 20, 20, 30],

    )
    write_include(
        root,
        f"{REVISION}rental_cost_horizons_table.qmd",
        f"data/{REVISION}rental_cost_horizons.csv",
        ["Blocks", "Hours", "Prorated BTC", "Minimum-lease BTC", "Minimum-lease USD"],
        [
            [
                str(row["analytical_horizon_blocks"]),
                row["analytical_horizon_hours"],
                row["theoretical_prorated_cost_btc"],
                row["actual_minimum_lease_cost_btc"],
                row["actual_minimum_lease_cost_usd"],
            ]
            for row in cost_summary_rows
        ],
        ["right", "right", "right", "right", "right"],
    )
    write_include(
        root,
        f"{REVISION}rental_listing_audit_table.qmd",
        f"data/{REVISION}rental_market_listings.csv",
        [
            "Rig",
            "Status",
            "Advertised MH/s",
            "Ask",
            "Price unit",
            "Minimum hours",
            "Minimum BTC",
        ],
        [
            [
                row["rig_id"],
                row["status"],
                row["advertised_hashrate_mhps"],
                row["ask_btc_per_mh_day"],
                row["price_unit"],
                row["minimum_rental_hours"],
                row["minimum_contractual_price_btc"],
            ]
            for row in listing_rows
        ],
        ["right", "left", "right", "right", "left", "right", "right"],
        column_relative_widths=[10, 12, 12, 19, 18, 10, 19],
    )
    write_include(
        root,
        f"{REVISION}rental_cost_reconciliation_table.qmd",
        f"data/{REVISION}rental_cost_reconciliation.csv",
        ["Metric", "Value", "Unit", "Calculation"],
        [
            [
                row["metric"],
                row["value"],
                row["unit"],
                row["calculation"],
            ]
            for row in reconciliation_rows
        ],
        ["left", "right", "left", "left"],
    )
    return summary, available, curve_rows


def greedy_rental_selection(
    rigs: list[dict[str, Any]],
    required_mh: Decimal,
    blocks: int,
) -> dict[str, Any]:
    if required_mh <= 0:
        return {
            "sufficient": True,
            "selected_mh": D(0),
            "rigs": 0,
            "theoretical_btc": D(0),
            "minimum_btc": D(0),
        }
    selected_mh = D(0)
    theoretical = D(0)
    minimum = D(0)
    selected = 0
    hours = D(blocks) / D(60)
    for rig in rigs:
        selected += 1
        selected_mh += rig["advertised_mh"]
        theoretical += rig["daily_cost_btc"] * hours / D(24)
        minimum += (
            rig["daily_cost_btc"] * max(hours, rig["minimum_hours"]) / D(24)
        )
        if selected_mh > required_mh:
            break
    return {
        "sufficient": selected_mh > required_mh,
        "selected_mh": selected_mh,
        "rigs": selected,
        "theoretical_btc": theoretical,
        "minimum_btc": minimum,
    }


def export_attack_capacity(
    root: Path,
    config: dict[str, Any],
    current_hashrate_mh: Decimal,
    rental_summary: dict[str, Any],
    rigs: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    empirical = config["empirical_security"]
    rental = D(rental_summary["advertised_available_mh"])
    btc_usd = D(rental_summary["btc_usd"])
    rows: list[dict[str, Any]] = []
    for reduction in empirical["honest_hashrate_reduction_stress_pct"]:
        honest = current_hashrate_mh * (D(100) - D(reduction)) / D(100)
        for owned in empirical["owned_hashrate_stress_mh"]:
            owned_hash = D(owned)
            attack_hash = rental + owned_hash
            for blocks in empirical["rental_horizons_blocks"]:
                required_rental = max(D(0), honest - owned_hash)
                selection = greedy_rental_selection(rigs, required_rental, int(blocks))
                rows.append(
                    {
                        "honest_hashrate_reduction_stress_pct": reduction,
                        "honest_hashrate_mhps": fmt_decimal(honest, 6),
                        "configured_owned_hashrate_mhps": fmt_decimal(owned_hash, 6),
                        "visible_rental_hashrate_mhps": fmt_decimal(rental, 6),
                        "rental_pct_pre_existing_honest_hashrate": fmt_decimal(
                            rental * D(100) / honest if honest else D(0), 4
                        ),
                        "rental_pct_combined_honest_plus_rental_hashrate": fmt_decimal(
                            rental * D(100) / (honest + rental) if honest + rental else D(0),
                            4,
                        ),
                        "rental_plus_owned_hashrate_mhps": fmt_decimal(attack_hash, 6),
                        "additional_hash_required_to_exceed_honest_mhps": fmt_decimal(
                            max(D(0), honest - attack_hash), 6
                        ),
                        "visible_rental_capacity_alone_sufficient": str(rental > honest).lower(),
                        "rental_plus_owned_capacity_sufficient": str(
                            attack_hash > honest
                        ).lower(),
                        "analytical_horizon_blocks": blocks,
                        "greedy_selected_rigs": selection["rigs"],
                        "greedy_selected_rental_hashrate_mhps": fmt_decimal(
                            selection["selected_mh"], 6
                        ),
                        "visible_depth_sufficient_for_threshold": str(
                            selection["sufficient"]
                        ).lower(),
                        "theoretical_prorated_threshold_cost_btc": (
                            fmt_decimal(selection["theoretical_btc"], 12)
                            if selection["sufficient"]
                            else ""
                        ),
                        "actual_minimum_lease_threshold_cost_btc": (
                            fmt_decimal(selection["minimum_btc"], 12)
                            if selection["sufficient"]
                            else ""
                        ),
                        "actual_minimum_lease_threshold_cost_usd": (
                            fmt_decimal(selection["minimum_btc"] * btc_usd, 6)
                            if selection["sufficient"]
                            else ""
                        ),
                        "evidence_class": (
                            "observed rental asks plus speculative honest-hash reduction "
                            "and owned-hash stress inputs"
                        ),
                    }
                )
    write_csv(root / "data" / f"{REVISION}rental_attack_capacity.csv", rows)
    baseline_rows = [
        row
        for row in rows
        if D(str(row["configured_owned_hashrate_mhps"])) == 0
        and int(row["analytical_horizon_blocks"]) == 144
    ]
    write_include(
        root,
        f"{REVISION}rental_attack_capacity_table.qmd",
        f"data/{REVISION}rental_attack_capacity.csv",
        [
            "Honest-hash reduction",
            "Honest MH/s",
            "Rental / honest",
            "Rental / combined",
            "Rental alone exceeds honest?",
            "Min 24 h ask cost if sufficient",
        ],
        [
            [
                f"{row['honest_hashrate_reduction_stress_pct']}%",
                row["honest_hashrate_mhps"],
                f"{row['rental_pct_pre_existing_honest_hashrate']}%",
                f"{row['rental_pct_combined_honest_plus_rental_hashrate']}%",
                row["visible_rental_capacity_alone_sufficient"],
                (
                    f"${row['actual_minimum_lease_threshold_cost_usd']}"
                    if row["actual_minimum_lease_threshold_cost_usd"]
                    else "insufficient visible depth"
                ),
            ]
            for row in baseline_rows
        ],
        ["right", "right", "right", "right", "center", "right"],
    )
    return rows


def parse_book(payload: Any, venue: str) -> tuple[list[tuple[Decimal, Decimal]], list[tuple[Decimal, Decimal]]]:
    if venue == "NestEx":
        bids = [(D(price), D(str(amount))) for price, amount in payload["bids"].items()]
        asks = [(D(price), D(str(amount))) for price, amount in payload["asks"].items()]
    else:
        bids = [(D(str(price)), D(str(amount))) for price, amount in payload["bids"]]
        asks = [(D(str(price)), D(str(amount))) for price, amount in payload["asks"]]
    return sorted(bids, reverse=True), sorted(asks)


def walk_sell(
    bids: list[tuple[Decimal, Decimal]], quantity: Decimal
) -> dict[str, Any]:
    remaining = quantity
    proceeds = D(0)
    worst: Decimal | None = None
    for price, available in bids:
        filled = min(remaining, available)
        proceeds += filled * price
        remaining -= filled
        if filled:
            worst = price
        if remaining <= 0:
            break
    filled_total = quantity - remaining
    average = proceeds / filled_total if filled_total else D(0)
    return {
        "requested": quantity,
        "filled": filled_total,
        "remaining": remaining,
        "proceeds": proceeds,
        "average_price": average,
        "worst_price": worst,
        "complete": remaining <= 0,
    }


def export_exchange_liquidity(
    root: Path,
    snapshot_dir: Path,
    config: dict[str, Any],
    daily_issuance_rin: Decimal,
) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    depths = [D(value) for value in config["empirical_security"]["order_book_depth_pct"]]
    ticker = read_json(snapshot_dir / "nestex_rin_usdt_ticker.json")
    venue_inputs = [
        (
            "NestEx",
            read_json(snapshot_dir / "nestex_rin_usdt_orderbook.json"),
            D(ticker["base_volume"]),
            D(ticker["target_volume"]),
            D(ticker["last_price"]),
            "24-hour ticker volume",
        ),
        (
            "Rabid Rabbit",
            read_json(snapshot_dir / "rabid_rabbit_rin_usdt_orderbook.json"),
            None,
            None,
            None,
            "24-hour volume unavailable in frozen public endpoint",
        ),
    ]
    rows: list[dict[str, Any]] = []
    venue_summary: dict[str, Any] = {}
    for venue, payload, base_volume, quote_volume, last_price, volume_status in venue_inputs:
        bids, asks = parse_book(payload, venue)
        best_bid = bids[0][0] if bids else D(0)
        best_ask = asks[0][0] if asks else D(0)
        midpoint = (best_bid + best_ask) / D(2) if best_bid and best_ask else D(0)
        spread_pct = (best_ask - best_bid) * D(100) / midpoint if midpoint else D(0)
        sale = walk_sell(bids, daily_issuance_rin)
        impact = (
            (best_bid - sale["average_price"]) * D(100) / best_bid
            if best_bid and sale["filled"]
            else D(0)
        )
        venue_summary[venue] = {
            "best_bid": best_bid,
            "best_ask": best_ask,
            "spread_pct": spread_pct,
            "sale": sale,
            "base_volume": base_volume,
            "quote_volume": quote_volume,
            "last_price": last_price,
            "volume_status": volume_status,
        }
        for depth in depths:
            bid_floor = best_bid * (D(1) - depth / D(100))
            ask_ceiling = best_ask * (D(1) + depth / D(100))
            bid_levels = [(price, amount) for price, amount in bids if price >= bid_floor]
            ask_levels = [(price, amount) for price, amount in asks if price <= ask_ceiling]
            bid_quantity = sum((amount for _, amount in bid_levels), D(0))
            ask_quantity = sum((amount for _, amount in ask_levels), D(0))
            bid_quote = sum((price * amount for price, amount in bid_levels), D(0))
            ask_quote = sum((price * amount for price, amount in ask_levels), D(0))
            rows.append(
                {
                    "venue": venue,
                    "pair": "RIN/USDT",
                    "best_bid_usdt": fmt_decimal(best_bid, 12),
                    "best_ask_usdt": fmt_decimal(best_ask, 12),
                    "spread_pct_midpoint": fmt_decimal(spread_pct, 6),
                    "depth_band_pct": fmt_decimal(depth, 2),
                    "bid_depth_rin": fmt_decimal(bid_quantity, 8),
                    "bid_depth_usdt": fmt_decimal(bid_quote, 8),
                    "ask_depth_rin": fmt_decimal(ask_quantity, 8),
                    "ask_depth_usdt": fmt_decimal(ask_quote, 8),
                    "reported_24h_base_volume_rin": (
                        fmt_decimal(base_volume, 8) if base_volume is not None else ""
                    ),
                    "reported_24h_quote_volume_usdt": (
                        fmt_decimal(quote_volume, 8) if quote_volume is not None else ""
                    ),
                    "daily_scheduled_issuance_rin": fmt_decimal(daily_issuance_rin),
                    "daily_issuance_pct_reported_volume": (
                        fmt_decimal(daily_issuance_rin * D(100) / base_volume, 4)
                        if base_volume
                        else ""
                    ),
                    "sell_one_day_issuance_complete": str(sale["complete"]).lower(),
                    "sell_one_day_issuance_average_price_usdt": fmt_decimal(
                        sale["average_price"], 12
                    ),
                    "sell_one_day_issuance_worst_price_usdt": (
                        fmt_decimal(sale["worst_price"], 12)
                        if sale["worst_price"] is not None
                        else ""
                    ),
                    "sell_one_day_issuance_impact_from_best_bid_pct": fmt_decimal(
                        impact, 6
                    ),
                    "volume_evidence_status": volume_status,
                    "evidence_class": "directly observed order book; derived depth and sale walk",
                }
            )
    write_csv(root / "data" / f"{REVISION}exchange_liquidity.csv", rows)
    include_rows = []
    for venue in ("NestEx", "Rabid Rabbit"):
        summary = venue_summary[venue]
        sale = summary["sale"]
        five = next(
            row for row in rows if row["venue"] == venue and D(row["depth_band_pct"]) == D(5)
        )
        include_rows.append(
            [
                venue,
                fmt_decimal(summary["best_bid"], 8),
                fmt_decimal(summary["best_ask"], 8),
                fmt_decimal(summary["spread_pct"], 2),
                five["bid_depth_rin"],
                (
                    five["reported_24h_base_volume_rin"]
                    if five["reported_24h_base_volume_rin"]
                    else "unavailable"
                ),
                (
                    f"{fmt_decimal(sale['average_price'], 8)} "
                    f"({'complete' if sale['complete'] else 'partial'})"
                ),
            ]
        )
    write_include(
        root,
        f"{REVISION}exchange_liquidity_table.qmd",
        f"data/{REVISION}exchange_liquidity.csv",
        [
            "Venue",
            "Best bid",
            "Best ask",
            "Spread, %",
            "Bid depth within 5%, RIN",
            "Reported 24 h volume, RIN",
            "9,000 RIN sale-walk average",
        ],
        include_rows,
        ["left", "right", "right", "right", "right", "right", "right"],
        column_relative_widths=[10, 14, 14, 12, 15, 19, 16]
    )
    return rows, venue_summary


def export_fee_replacement(
    root: Path,
    summaries: dict[int, dict[str, Any]],
    config: dict[str, Any],
) -> list[dict[str, Any]]:
    window = int(config["empirical_security"]["primary_fee_window_days"])
    baseline = summaries[window]
    observed_mean = D(str(baseline["block_fees"]["mean"]))
    observed_median = D(str(baseline["block_fees"]["median"]))
    observed_tx_median = D(str(baseline["tx_fees"]["median"]))
    shocks = read_csv(root / "data" / f"{REVISION}reward_boundary_shocks.csv")
    rows: list[dict[str, Any]] = []
    for item in shocks:
        before = D(item["subsidy_before_base_units"])
        after = D(item["subsidy_after_base_units"])
        required = D(item["fee_replacement_base_units_per_block"])
        rows.append(
            {
                "scenario_id": item["scenario_id"],
                "scenario_display_id": item["scenario_display_id"],
                "boundary_height": item["boundary_height"],
                "boundary_type": item["boundary_type"],
                "subsidy_before_rin": item["subsidy_before_rin"],
                "subsidy_after_rin": item["subsidy_after_rin"],
                "required_additional_fee_rin_per_block": item[
                    "fee_replacement_rin_per_block"
                ],
                "observed_window_days": window,
                "observed_mean_total_fee_base_units_per_block": fmt_decimal(
                    observed_mean, 4
                ),
                "observed_median_total_fee_base_units_per_block": fmt_decimal(
                    observed_median, 4
                ),
                "required_multiple_of_observed_mean_fee": (
                    fmt_decimal(required / observed_mean, 4) if observed_mean else ""
                ),
                "required_multiple_of_observed_median_fee": (
                    fmt_decimal(required / observed_median, 4) if observed_median else ""
                ),
                "median_fee_zero": str(observed_median == 0).lower(),
                "observed_median_fee_per_non_coinbase_transaction_base_units": fmt_decimal(
                    observed_tx_median, 4
                ),
                "required_transactions_at_observed_median_transaction_fee": (
                    math.ceil(required / observed_tx_median)
                    if observed_tx_median and required
                    else 0
                ),
                "fee_share_before_boundary_pct": fmt_decimal(
                    observed_mean * D(100) / (before + observed_mean)
                    if before + observed_mean
                    else D(0),
                    8,
                ),
                "fee_share_after_boundary_with_observed_fees_pct": fmt_decimal(
                    observed_mean * D(100) / (after + observed_mean)
                    if after + observed_mean
                    else D(0),
                    8,
                ),
                "fee_share_after_boundary_if_revenue_fully_replaced_pct": fmt_decimal(
                    (observed_mean + required)
                    * D(100)
                    / (after + observed_mean + required)
                    if after + observed_mean + required
                    else D(0),
                    8,
                ),
                "evidence_class": (
                    "consensus-deterministic boundary requirement calibrated to "
                    "derived observed fee distributions"
                ),
            }
        )
    write_csv(root / "data" / f"{REVISION}fee_replacement_calibrated.csv", rows)
    activation_rows = [row for row in rows if row["boundary_type"] == "activation"]
    write_include(
        root,
        f"{REVISION}fee_replacement_calibrated_table.qmd",
        f"data/{REVISION}fee_replacement_calibrated.csv",
        [
            "Scenario",
            "Before",
            "After",
            "Additional fee required",
            "Multiple of 90 d mean",
            "Transactions at median fee",
        ],
        [
            [
                row["scenario_display_id"],
                row["subsidy_before_rin"],
                row["subsidy_after_rin"],
                row["required_additional_fee_rin_per_block"],
                (
                    row["required_multiple_of_observed_mean_fee"]
                    if row["required_multiple_of_observed_mean_fee"]
                    else "undefined"
                ),
                str(row["required_transactions_at_observed_median_transaction_fee"]),
            ]
            for row in activation_rows
        ],
        ["center", "right", "right", "right", "right", "right"],
    )
    return rows


def export_hardware_protocol(root: Path) -> None:
    dataset_rows = [
        {
            "dataset_status": "pending",
            "hardware_model": "",
            "hardware_class": "",
            "miner_software_and_version": "",
            "hashrate_mhps": "",
            "wall_power_watts": "",
            "hashrate_per_watt": "",
            "electricity_cost_per_mh_day": "",
            "acquisition_cost": "",
            "source": (
                "No sufficient independently reproducible RinHash hashrate-and-wall-power "
                "dataset was identified in the frozen evidence."
            ),
            "test_date": "",
            "evidence_class": "missing empirical measurement; not modeled as observed data",
        }
    ]
    protocol_rows = [
        {
            "step": 1,
            "measurement": "Hardware and software identity",
            "requirement": (
                "Record exact CPU/GPU/FPGA model, memory, firmware/driver, operating "
                "system, miner repository commit and build flags."
            ),
        },
        {
            "step": 2,
            "measurement": "Controlled hashrate",
            "requirement": (
                "Run a fixed-duration warm-up and measurement interval against a named "
                "pool or local validation target; retain accepted, rejected and stale shares."
            ),
        },
        {
            "step": 3,
            "measurement": "Wall power",
            "requirement": (
                "Measure whole-system wall power with a calibrated meter; report idle "
                "baseline, load mean, variance, clocks and power limits."
            ),
        },
        {
            "step": 4,
            "measurement": "Economics",
            "requirement": (
                "Calculate MH/s per watt and electricity cost per MH/day under an explicit "
                "tariff; report acquisition price and date separately."
            ),
        },
        {
            "step": 5,
            "measurement": "Reproducibility",
            "requirement": (
                "Repeat on at least two systems where practical and publish raw logs, "
                "meter data, configuration and checksums."
            ),
        },
    ]
    write_csv(root / "data" / f"{REVISION}hardware_benchmarks.csv", dataset_rows)
    write_csv(root / "data" / f"{REVISION}hardware_benchmark_protocol.csv", protocol_rows)
    write_include(
        root,
        f"{REVISION}hardware_benchmark_status_table.qmd",
        f"data/{REVISION}hardware_benchmarks.csv",
        ["Status", "Available evidence", "Required next step"],
        [
            [
                "Pending",
                (
                    "MRR listings expose names and advertised hashrate, but not "
                    "independently measured wall power or delivered rate."
                ),
                "Execute and publish the controlled benchmark protocol.",
            ]
        ],
        ["center", "left", "left"],
        column_relative_widths=[20, 40, 40],
    )


def export_empirical_scenario_comparison(
    root: Path,
    snapshot_dir: Path,
    summaries: dict[int, dict[str, Any]],
    config: dict[str, Any],
) -> list[dict[str, Any]]:
    primary_window = int(config["empirical_security"]["primary_fee_window_days"])
    observed_fee = D(str(summaries[primary_window]["block_fees"]["mean"]))
    ticker = read_json(snapshot_dir / "nestex_rin_usdt_ticker.json")
    price = D(ticker["last_price"])
    shocks = [
        row
        for row in read_csv(root / "data" / f"{REVISION}reward_boundary_shocks.csv")
        if row["boundary_type"] == "activation"
    ]
    normalized = read_csv(root / "data" / f"{REVISION}security_comparison_by_horizon.csv")
    normalized_10y = {
        row["scenario_id"]: row
        for row in normalized
        if row["horizon_years"] == "10"
    }
    rows: list[dict[str, Any]] = []
    for item in shocks:
        subsidy = D(item["subsidy_after_base_units"])
        block_revenue_rin = (subsidy + observed_fee) / COIN
        norm = normalized_10y.get(item["scenario_id"])
        rows.append(
            {
                "scenario_id": item["scenario_id"],
                "scenario_display_id": item["scenario_display_id"],
                "activation_subsidy_rin": item["subsidy_after_rin"],
                "observed_90d_mean_fee_rin_per_block": fmt_decimal(observed_fee / COIN),
                "activation_block_revenue_rin_at_observed_fee": fmt_decimal(block_revenue_rin),
                "activation_block_revenue_usdt_at_snapshot_marginal_price": fmt_decimal(
                    block_revenue_rin * price, 8
                ),
                "activation_nominal_revenue_shock_pct": item[
                    "nominal_revenue_shock_pct"
                ],
                "normalized_10y_revenue_index": (
                    norm["annual_realizable_miner_revenue_index"] if norm else ""
                ),
                "observed_baseline_interpretation": (
                    "Snapshot price and 90-day mean fee held constant; not an activation forecast."
                ),
                "evidence_class": (
                    "deterministic subsidy plus derived observed fee and directly observed "
                    "marginal price; normalized column remains sensitivity-only"
                ),
            }
        )
    write_csv(root / "data" / f"{REVISION}empirical_scenario_security_comparison.csv", rows)
    write_include(
        root,
        f"{REVISION}empirical_scenario_security_comparison_table.qmd",
        f"data/{REVISION}empirical_scenario_security_comparison.csv",
        [
            "Scenario",
            "Activation subsidy",
            "Block revenue at observed fee",
            "Marginal USDT value",
            "Boundary shock, %",
            "Normalized 10 y index",
        ],
        [
            [
                row["scenario_display_id"],
                row["activation_subsidy_rin"],
                row["activation_block_revenue_rin_at_observed_fee"],
                row["activation_block_revenue_usdt_at_snapshot_marginal_price"],
                row["activation_nominal_revenue_shock_pct"],
                row["normalized_10y_revenue_index"],
            ]
            for row in rows
        ],
        ["center", "right", "right", "right", "right", "right"],
    )
    return rows


def export_current_snapshot(
    root: Path,
    snapshot_dir: Path,
    manifest: dict[str, Any],
    summaries: dict[int, dict[str, Any]],
    rental: dict[str, Any],
    liquidity: dict[str, Any],
    config: dict[str, Any],
) -> tuple[list[dict[str, Any]], Decimal, Decimal]:
    mining = read_json(snapshot_dir / "node_mining_info.json")
    tip = read_json(snapshot_dir / "node_tip_block.json")
    explorer = read_json(snapshot_dir / "explorer_summary.json")
    ticker = read_json(snapshot_dir / "nestex_rin_usdt_ticker.json")
    price = read_json(snapshot_dir / "explorer_current_price.json")
    network_hashrate_hps = D(str(mining["networkhashps"]))
    network_hashrate_mh = network_hashrate_hps / D(1_000_000)
    subsidy = D(tip["stats"]["subsidy"]) / COIN
    target_blocks_day = D(86400) / D(config["network"]["target_block_seconds"])
    daily_issuance = subsidy * target_blocks_day
    primary_window = int(config["empirical_security"]["primary_fee_window_days"])
    ninety = summaries[primary_window]

    node_source = source_entry(manifest, "node_mining_info.json")
    tip_source = source_entry(manifest, "node_tip_block.json")
    explorer_source = source_entry(manifest, "explorer_summary.json")
    mrr_source = source_entry(manifest, "mrr_rinhash_rigs.json")
    nestex_source = source_entry(manifest, "nestex_rin_usdt_ticker.json")
    rows: list[dict[str, Any]] = []

    def add(
        metric: str,
        value: Any,
        unit: str,
        method: str,
        evidence_class: str,
        source: dict[str, Any],
        status: str,
    ) -> None:
        rows.append(
            {
                "metric": metric,
                "value": value,
                "unit": unit,
                "calculation_method": method,
                "evidence_class": evidence_class,
                "source_url": source["source_url"],
                "retrieved_utc": source["retrieved_utc"],
                "evidence_status": status,
            }
        )

    add(
        "Local-node block height",
        int(mining["blocks"]),
        "blocks",
        "getmininginfo",
        "directly observed",
        node_source,
        "fully synced local node at snapshot time",
    )
    add(
        "Explorer block height",
        int(explorer["blockcount"]),
        "blocks",
        "explorer summary endpoint",
        "directly observed",
        explorer_source,
        "independent tip cross-check",
    )
    add(
        "Maximum current block subsidy",
        fmt_decimal(subsidy),
        "RIN/block",
        "getblockstats subsidy at frozen tip",
        "consensus-deterministic and directly observed",
        tip_source,
        "maximum permitted subsidy; underclaiming not assessed here",
    )
    add(
        "Current difficulty",
        fmt_decimal(D(str(mining["difficulty"])), 12),
        "difficulty",
        "getmininginfo",
        "directly observed",
        node_source,
        "point-in-time",
    )
    add(
        "Current network hashrate estimate",
        fmt_decimal(network_hashrate_mh, 8),
        "MH/s",
        "getmininginfo networkhashps",
        "directly observed node estimate",
        node_source,
        "point-in-time estimate",
    )
    add(
        "Explorer RIN price",
        fmt_decimal(D(price["last_price_usd"]), 12),
        "USD/RIN",
        "explorer current-price endpoint",
        "directly observed aggregate",
        source_entry(manifest, "explorer_current_price.json"),
        "venue composition not asserted",
    )
    add(
        "NestEx RIN price",
        fmt_decimal(D(ticker["last_price"]), 12),
        "USDT/RIN",
        "RIN_USDT ticker last price",
        "directly observed venue quote",
        nestex_source,
        "marginal trade price, not realizable depth",
    )
    add(
        "Target blocks per day",
        fmt_decimal(target_blocks_day, 2),
        "blocks/day",
        "86,400 seconds / 60-second consensus target",
        "consensus-deterministic",
        tip_source,
        "target, not observed production",
    )
    add(
        "Scheduled daily issuance",
        fmt_decimal(daily_issuance),
        "RIN/day",
        "tip subsidy x target blocks/day",
        "derived consensus-deterministic",
        tip_source,
        "maximum scheduled value",
    )
    add(
        "Scheduled daily issuance at explorer price",
        fmt_decimal(daily_issuance * D(price["last_price_usd"]), 8),
        "USD/day",
        "scheduled RIN/day x frozen explorer marginal price",
        "derived from observed data",
        explorer_source,
        "not realizable proceeds",
    )
    add(
        "Scheduled daily issuance at NestEx price",
        fmt_decimal(daily_issuance * D(ticker["last_price"]), 8),
        "USDT/day",
        "scheduled RIN/day x frozen NestEx marginal price",
        "derived from observed data",
        nestex_source,
        "not realizable proceeds",
    )
    add(
        f"Observed non-coinbase transactions ({primary_window} d)",
        ninety["non_coinbase_transaction_count"],
        "transactions",
        "exact count from local getblockstats history",
        "derived from observed data",
        source_entry(manifest, "node_block_history_365d.jsonl.gz"),
        "complete frozen window",
    )
    add(
        f"Mean total fees per block ({primary_window} d)",
        fmt_decimal(D(str(ninety["block_fees"]["mean"])) / COIN),
        "RIN/block",
        "sum of getblockstats totalfee / all blocks",
        "derived from observed data",
        source_entry(manifest, "node_block_history_365d.jsonl.gz"),
        "includes zero-fee blocks",
    )
    add(
        f"Median total fees per block ({primary_window} d)",
        fmt_decimal(D(str(ninety["block_fees"]["median"])) / COIN),
        "RIN/block",
        "median getblockstats totalfee across all blocks",
        "derived from observed data",
        source_entry(manifest, "node_block_history_365d.jsonl.gz"),
        "zero because most blocks had no non-coinbase transaction",
    )
    add(
        f"Fee share of miner revenue ({primary_window} d)",
        fmt_decimal(ninety["aggregate_fee_share_pct"], 8),
        "%",
        "sum(totalfee) / [sum(subsidy) + sum(totalfee)]",
        "derived from observed data",
        source_entry(manifest, "node_block_history_365d.jsonl.gz"),
        "uses total fees per block",
    )
    add(
        f"Explorer-indexed orphaned blocks ({primary_window} d)",
        ninety["indexed_orphaned_blocks"],
        "blocks",
        "count of getlastorphans records within the frozen window",
        "directly observed explorer index",
        source_entry(manifest, "explorer_last_orphans_365d.jsonl.gz"),
        (
            "endpoint exhausted below one page; explorer index retention and "
            "pre-index history not independently verified"
        ),
    )
    add(
        f"Explorer-indexed orphan incidence ({primary_window} d)",
        fmt_decimal(
            D(ninety["indexed_orphaned_blocks"])
            * D(100)
            / D(ninety["block_count"] + ninety["indexed_orphaned_blocks"]),
            6,
        ),
        "%",
        "indexed orphans / (main-chain blocks + indexed orphans)",
        "derived from observed explorer index and local chain data",
        source_entry(manifest, "explorer_last_orphans_365d.jsonl.gz"),
        "index-based incidence, not independently reconstructed from raw peer data",
    )
    add(
        "Visible RinHash rental capacity",
        fmt_decimal(rental["advertised_available_mh"], 6),
        "MH/s",
        "sum of available API-online advertised listings",
        "directly observed asks",
        mrr_source,
        "delivery unverified",
    )
    add(
        "Visible rental capacity / current node hashrate",
        fmt_decimal(rental["capacity_pct_honest"], 2),
        "%",
        "advertised rental MH/s / current networkhashps estimate",
        "derived from observed data",
        mrr_source,
        "point-in-time ratio",
    )
    add(
        "Weighted visible rental ask",
        fmt_decimal(rental["weighted_ask_btc_per_mh_day"], 12),
        "BTC/MH/day",
        "capacity-weighted quoted asks",
        "derived from directly observed asks",
        mrr_source,
        "not an executed or market-clearing price",
    )
    add(
        "NestEx bid depth within 5%",
        next(
            row["bid_depth_rin"]
            for row in read_csv(root / "data" / f"{REVISION}exchange_liquidity.csv")
            if row["venue"] == "NestEx" and D(row["depth_band_pct"]) == D(5)
        ),
        "RIN",
        "sum of frozen bids no more than 5% below best bid",
        "derived from observed order book",
        source_entry(manifest, "nestex_rin_usdt_orderbook.json"),
        "point-in-time visible depth",
    )
    write_csv(root / "data" / f"{REVISION}empirical_network_snapshot.csv", rows)
    selected_metrics = {
        "Local-node block height",
        "Maximum current block subsidy",
        "Current difficulty",
        "Current network hashrate estimate",
        "NestEx RIN price",
        "Scheduled daily issuance",
        f"Observed non-coinbase transactions ({primary_window} d)",
        f"Mean total fees per block ({primary_window} d)",
        f"Fee share of miner revenue ({primary_window} d)",
        f"Explorer-indexed orphaned blocks ({primary_window} d)",
        "Visible RinHash rental capacity",
        "Visible rental capacity / current node hashrate",
        "NestEx bid depth within 5%",
    }
    write_include(
        root,
        f"{REVISION}empirical_network_snapshot_table.qmd",
        f"data/{REVISION}empirical_network_snapshot.csv",
        ["Metric", "Value", "Unit", "Evidence class"],
        [
            [row["metric"], str(row["value"]), row["unit"], row["evidence_class"]]
            for row in rows
            if row["metric"] in selected_metrics
        ],
        ["left", "right", "left", "left"],
        column_relative_widths=[30, 20, 20, 30],
    )
    return rows, network_hashrate_mh, daily_issuance


def draw_line_chart(
    path: Path,
    title: str,
    x_label: str,
    y_label: str,
    series: list[tuple[str, tuple[int, int, int], list[tuple[float, float]]]],
) -> None:
    width, height = 1800, 930
    left, right, top, bottom = 145, 420, 100, 120
    plot_width = width - left - right
    plot_height = height - top - bottom
    image = Image.new("RGB", (width, height), "white")
    draw = ImageDraw.Draw(image)
    try:
        title_font = ImageFont.truetype(
            "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 30
        )
        font = ImageFont.truetype(
            "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 18
        )
        small = ImageFont.truetype(
            "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 15
        )
    except OSError:
        title_font = font = small = ImageFont.load_default()

    all_points = [point for _, _, points in series for point in points]
    x_min = min((point[0] for point in all_points), default=0)
    x_max = max((point[0] for point in all_points), default=1)
    y_min = min((point[1] for point in all_points), default=0)
    y_max = max((point[1] for point in all_points), default=1)
    if x_max == x_min:
        x_max = x_min + 1
    if y_max == y_min:
        y_max = y_min + 1
    y_padding = (y_max - y_min) * 0.05
    y_min = min(0, y_min - y_padding)
    y_max += y_padding

    draw.text((left, 28), title, fill=(20, 20, 20), font=title_font)
    draw.text((20, 70), y_label, fill=(20, 20, 20), font=font)
    draw.text(
        (left + plot_width // 2 - 120, height - 50),
        x_label,
        fill=(20, 20, 20),
        font=font,
    )
    for index in range(6):
        x = left + index * plot_width / 5
        y = top + index * plot_height / 5
        draw.line((x, top, x, top + plot_height), fill=(225, 225, 225))
        draw.line((left, y, left + plot_width, y), fill=(225, 225, 225))
        x_value = x_min + (x_max - x_min) * index / 5
        y_value = y_max - (y_max - y_min) * index / 5
        draw.text((x - 15, top + plot_height + 12), f"{x_value:.0f}", fill=(40, 40, 40), font=small)
        draw.text((22, y - 8), f"{y_value:.4g}", fill=(40, 40, 40), font=small)
    draw.rectangle((left, top, left + plot_width, top + plot_height), outline=(80, 80, 80))

    def position(point: tuple[float, float]) -> tuple[float, float]:
        x, y = point
        return (
            left + (x - x_min) / (x_max - x_min) * plot_width,
            top + plot_height - (y - y_min) / (y_max - y_min) * plot_height,
        )

    legend_x = left + plot_width + 35
    draw.text((legend_x, top), "Series", fill=(20, 20, 20), font=title_font)
    legend_y = top + 48
    for label, color, points in series:
        coordinates = [position(point) for point in points]
        if len(coordinates) > 1:
            draw.line(coordinates, fill=color, width=3)
        draw.rectangle((legend_x, legend_y, legend_x + 26, legend_y + 16), fill=color)
        wrapped = textwrap.wrap(label, width=34) or [label]
        for offset, text in enumerate(wrapped):
            draw.text(
                (legend_x + 36, legend_y + offset * 20),
                text,
                fill=(20, 20, 20),
                font=small,
            )
        legend_y += max(40, len(wrapped) * 22 + 8)
    path.parent.mkdir(parents=True, exist_ok=True)
    image.save(path)


def draw_bar_chart(
    path: Path,
    title: str,
    y_label: str,
    labels: list[str],
    values: list[float],
    color: tuple[int, int, int],
) -> None:
    width, height = 1650, 900
    left, right, top, bottom = 150, 80, 105, 190
    plot_width = width - left - right
    plot_height = height - top - bottom
    image = Image.new("RGB", (width, height), "white")
    draw = ImageDraw.Draw(image)
    try:
        title_font = ImageFont.truetype(
            "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 29
        )
        font = ImageFont.truetype(
            "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 17
        )
        small = ImageFont.truetype(
            "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 14
        )
    except OSError:
        title_font = font = small = ImageFont.load_default()
    maximum = max(values, default=1) * 1.10 or 1
    draw.text((left, 28), title, fill=(20, 20, 20), font=title_font)
    draw.text((20, 72), y_label, fill=(20, 20, 20), font=font)
    for index in range(6):
        y = top + index * plot_height / 5
        value = maximum * (5 - index) / 5
        draw.line((left, y, left + plot_width, y), fill=(225, 225, 225))
        draw.text((28, y - 8), f"{value:.4g}", fill=(40, 40, 40), font=small)
    slot = plot_width / max(1, len(values))
    for index, (label, value) in enumerate(zip(labels, values)):
        x0 = left + index * slot + slot * 0.15
        x1 = left + (index + 1) * slot - slot * 0.15
        y0 = top + plot_height - value / maximum * plot_height
        draw.rectangle((x0, y0, x1, top + plot_height), fill=color)
        draw.text((x0, y0 - 24), f"{value:.4g}", fill=(30, 30, 30), font=small)
        for line_index, line in enumerate(textwrap.wrap(label, width=15)):
            draw.text(
                (x0, top + plot_height + 16 + line_index * 18),
                line,
                fill=(30, 30, 30),
                font=small,
            )
    draw.rectangle((left, top, left + plot_width, top + plot_height), outline=(80, 80, 80))
    path.parent.mkdir(parents=True, exist_ok=True)
    image.save(path)


def export_empirical_figures(
    root: Path,
    daily_hash: list[dict[str, Any]],
    daily_fees: list[dict[str, Any]],
    rental_curve: list[dict[str, Any]],
    attack_rows: list[dict[str, Any]],
    liquidity_rows: list[dict[str, Any]],
    scenario_rows: list[dict[str, Any]],
) -> None:
    hash_points = [
        (float(index), float(row["mean_rolling_hashrate_mhps"]))
        for index, row in enumerate(daily_hash)
    ]
    fee_points = [
        (float(index), float(row["mean_total_fee_rin_per_block"]))
        for index, row in enumerate(daily_fees)
    ]
    draw_line_chart(
        root / "figures" / f"{REVISION}empirical_hashrate_history_365d.png",
        "Observed rolling network hashrate - frozen 365-day window",
        "Days from window start",
        "MH/s",
        [("Daily mean of 120-block rolling estimate", COLORS["blue"], hash_points)],
    )
    draw_line_chart(
        root / "figures" / f"{REVISION}empirical_fee_per_block_history_365d.png",
        "Observed total transaction fees per block - frozen 365-day window",
        "Days from window start",
        "RIN/block",
        [("Daily mean including zero-fee blocks", COLORS["orange"], fee_points)],
    )
    draw_line_chart(
        root / "figures" / f"{REVISION}rental_cost_curve.png",
        "Visible RinHash rental ask-depth curve",
        "Cumulative advertised MH/s",
        "Minimum lease cost, USD",
        [
            (
                "Greedy order by quoted BTC/MH/day",
                COLORS["red"],
                [
                    (
                        float(row["cumulative_hashrate_mhps"]),
                        float(row["cumulative_minimum_contract_cost_usd"]),
                    )
                    for row in rental_curve
                ],
            )
        ],
    )
    baseline_attack = [
        row
        for row in attack_rows
        if D(row["configured_owned_hashrate_mhps"]) == 0
        and int(row["analytical_horizon_blocks"]) == 144
    ]
    draw_line_chart(
        root / "figures" / f"{REVISION}rental_network_hash_ratio.png",
        "Visible rental capacity relative to honest-network stress cases",
        "Assumed honest-hash reduction, %",
        "Percent",
        [
            (
                "Rental / pre-existing honest hash",
                COLORS["red"],
                [
                    (
                        float(row["honest_hashrate_reduction_stress_pct"]),
                        float(row["rental_pct_pre_existing_honest_hashrate"]),
                    )
                    for row in baseline_attack
                ],
            ),
            (
                "Rental / combined honest plus rental hash",
                COLORS["blue"],
                [
                    (
                        float(row["honest_hashrate_reduction_stress_pct"]),
                        float(row["rental_pct_combined_honest_plus_rental_hashrate"]),
                    )
                    for row in baseline_attack
                ],
            ),
        ],
    )
    five_depth = [
        row for row in liquidity_rows if D(row["depth_band_pct"]) == D(5)
    ]
    draw_bar_chart(
        root / "figures" / f"{REVISION}market_depth_vs_daily_issuance.png",
        "Visible bid depth within 5% compared with scheduled daily issuance",
        "RIN",
        [row["venue"] for row in five_depth] + ["Scheduled daily issuance"],
        [float(row["bid_depth_rin"]) for row in five_depth]
        + [float(five_depth[0]["daily_scheduled_issuance_rin"])],
        COLORS["green"],
    )
    draw_bar_chart(
        root / "figures" / f"{REVISION}empirical_scenario_security_activation.png",
        "Activation block revenue at frozen fee and marginal price baseline",
        "USDT/block",
        [row["scenario_display_id"] for row in scenario_rows],
        [
            float(row["activation_block_revenue_usdt_at_snapshot_marginal_price"])
            for row in scenario_rows
        ],
        COLORS["blue"],
    )


def validate_outputs(
    root: Path,
    config: dict[str, Any],
    manifest: dict[str, Any],
    summaries: dict[int, dict[str, Any]],
    transaction_fee_total: int,
    rental: dict[str, Any],
) -> None:
    manifest_history = source_entry(manifest, "node_block_history_365d.jsonl.gz")
    expected_fee_total = 0
    with gzip.open(root / manifest_history["path"], "rt", encoding="utf-8") as handle:
        for line in handle:
            expected_fee_total += int(json.loads(line)["total_fees_base_units"])
    if transaction_fee_total != expected_fee_total:
        raise ValueError("Transaction-fee total does not match block-history total")

    primary = summaries[int(config["empirical_security"]["primary_fee_window_days"])]
    fee_cases = {item["id"]: item for item in config["security_economics"]["fee_cases"]}
    if int(fee_cases["low"]["fee_per_block_base_units"]) != round(
        primary["block_fees"]["median"]
    ):
        raise ValueError("Low fee case is not anchored to the observed all-block median")
    if int(fee_cases["base"]["fee_per_block_base_units"]) != round(
        primary["block_fees"]["mean"]
    ):
        raise ValueError("Base fee case is not anchored to the observed all-block mean")
    if int(fee_cases["high"]["fee_per_block_base_units"]) != round(
        primary["active_block_fees"]["p90"]
    ):
        raise ValueError(
            "High fee case is not anchored to the observed active-block p90"
        )
    history = read_csv(root / "data" / f"{REVISION}historical_network_baseline.csv")
    if len(history) != 3:
        raise ValueError("Expected 30/90/365-day historical summaries")

    mrr = read_json(
        root
        / config["empirical_security"]["snapshot_path"]
        / "mrr_rinhash_rigs.json"
    )
    api_capacity = hashrate_to_mh(
        mrr["data"]["stats"]["available"]["hash"]["hash"],
        mrr["data"]["stats"]["available"]["hash"]["type"],
    )
    if abs(api_capacity - D(rental["advertised_available_mh"])) > D("0.000001"):
        raise ValueError("Rental aggregate mismatch")
    if rental["all_capacity_24h_cost_btc"] != D("0.000352921232500000"):
        raise ValueError("Unexpected all-capacity 24-hour rental ask")
    if rental["all_capacity_minimum_contract_cost_btc"] != D(
        "0.00009093210531250000"
    ):
        raise ValueError("Unexpected sum of listing minimum contractual prices")

    required = [
        f"data/{REVISION}empirical_network_snapshot.csv",
        f"data/{REVISION}historical_network_baseline.csv",
        f"data/{REVISION}hashrate_history.csv.gz",
        f"data/{REVISION}fee_per_block_history.csv.gz",
        f"data/{REVISION}orphan_history.csv",
        f"data/{REVISION}orphan_baseline.csv",
        f"data/{REVISION}rental_market_listings.csv",
        f"data/{REVISION}rental_cost_curve.csv",
        f"data/{REVISION}rental_cost_reconciliation.csv",
        f"data/{REVISION}rental_attack_capacity.csv",
        f"data/{REVISION}fee_replacement_calibrated.csv",
        f"data/{REVISION}exchange_liquidity.csv",
        f"data/{REVISION}hardware_benchmarks.csv",
        f"data/{REVISION}empirical_scenario_security_comparison.csv",
        f"figures/{REVISION}empirical_hashrate_history_365d.png",
        f"figures/{REVISION}empirical_fee_per_block_history_365d.png",
        f"figures/{REVISION}rental_cost_curve.png",
        f"figures/{REVISION}rental_network_hash_ratio.png",
        f"figures/{REVISION}market_depth_vs_daily_issuance.png",
        f"figures/{REVISION}empirical_scenario_security_activation.png",
        f"includes/{REVISION}rental_listing_audit_table.qmd",
        f"includes/{REVISION}rental_cost_reconciliation_table.qmd",
    ]
    for relative in required:
        path = root / relative
        if not path.exists() or path.stat().st_size == 0:
            raise ValueError(f"Missing empirical artifact: {relative}")


def main() -> None:
    root = Path.cwd()
    config = monetary.load_config(root)
    snapshot_dir = root / config["empirical_security"]["snapshot_path"]
    manifest = read_json(snapshot_dir / "SOURCE_MANIFEST.json")
    source_rows = verify_frozen_sources(root, manifest)
    write_csv(root / "data" / f"{REVISION}empirical_source_manifest.csv", source_rows)

    accumulators, transaction_block_times, daily_hash, daily_fees = block_history(
        root, snapshot_dir, config
    )
    tip = read_json(snapshot_dir / "node_tip_block.json")
    windows = [int(value) for value in config["empirical_security"]["history_windows_days"]]
    transaction_fees, transaction_fee_total = exact_transaction_fees(
        snapshot_dir,
        transaction_block_times,
        int(tip["header"]["time"]),
        windows,
    )
    orphan_summaries = orphan_baseline(
        root,
        snapshot_dir,
        int(tip["header"]["time"]),
        windows,
    )
    _, summaries = export_historical_baseline(
        root,
        snapshot_dir,
        config,
        accumulators,
        transaction_fees,
        orphan_summaries,
    )

    mining = read_json(snapshot_dir / "node_mining_info.json")
    current_hashrate_mh = D(str(mining["networkhashps"])) / D(1_000_000)
    kraken = read_json(snapshot_dir / "kraken_xbt_usd_ticker.json")
    btc_usd = D(kraken["result"]["XXBTZUSD"]["c"][0])
    rental, rigs, rental_curve = parse_rental_market(
        root, snapshot_dir, config, current_hashrate_mh, btc_usd
    )
    attack_rows = export_attack_capacity(
        root, config, current_hashrate_mh, rental, rigs
    )

    subsidy = D(tip["stats"]["subsidy"]) / COIN
    daily_issuance = (
        subsidy * D(86400) / D(config["network"]["target_block_seconds"])
    )
    liquidity_rows, liquidity = export_exchange_liquidity(
        root, snapshot_dir, config, daily_issuance
    )
    export_current_snapshot(
        root, snapshot_dir, manifest, summaries, rental, liquidity, config
    )
    export_hardware_protocol(root)
    export_fee_replacement(root, summaries, config)
    scenario_rows = export_empirical_scenario_comparison(
        root, snapshot_dir, summaries, config
    )
    export_empirical_figures(
        root,
        daily_hash,
        daily_fees,
        rental_curve,
        attack_rows,
        liquidity_rows,
        scenario_rows,
    )
    validate_outputs(
        root,
        config,
        manifest,
        summaries,
        transaction_fee_total,
        rental,
    )


if __name__ == "__main__":
    main()
