#!/usr/bin/env python3
"""Generate secondary normalized security-economics review artifacts.

This model consumes the same height-based subsidy schedules as the monetary
simulator. Price, hardware, response and liquidity inputs are explicit
normalized sensitivities. Fee cases are anchored to the frozen empirical
snapshot but are held constant in this secondary long-run model.
"""

from __future__ import annotations

import csv
import json
from decimal import Decimal, getcontext
from pathlib import Path

import simulate_monetary_scenarios as monetary


getcontext().prec = 80
REVISION = ""
D = Decimal


def write_csv(path: Path, rows: list[dict]) -> None:
    if not rows:
        raise ValueError(f"Refusing to write empty CSV: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=list(rows[0]),
            lineterminator="\n",
        )
        writer.writeheader()
        writer.writerows(rows)


def read_csv(path: Path) -> list[dict]:
    with path.open("r", newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def fmt(value: Decimal, places: int = 8) -> str:
    return f"{value.quantize(D(1).scaleb(-places)):f}"


def price_index(path: dict, years: Decimal) -> Decimal:
    initial = D(path["initial_price_index"])
    annual = D(1) + D(path["annual_change_pct"]) / D(100)
    return initial * (annual**years)


def fee_base_units(case: dict, years: Decimal) -> int:
    initial = D(case["fee_per_block_base_units"])
    annual = D(1) + D(case["annual_change_pct"]) / D(100)
    return int(initial * (annual**years))


def generated_header(source: str) -> str:
    return (
        "<!-- Generated by scripts/simulate_security_economics.py "
        f"from {source}. Do not edit by hand. -->\n\n"
    )


def md_table(headers: list[str], rows: list[list[str]], alignments: list[str], column_relative_widths: list[int] | None = None,) -> str:
    if column_relative_widths is not None:
        if any(
            isinstance(width, bool) or not isinstance(width, int) or width <= 0
            for width in column_relative_widths
        ):
            raise ValueError("Markdown table column widths must be positive integers")
    markers = {"left": ":---", "center": ":---:", "right": "---:"}
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join(markers[item] for item in alignments) + " |",
    ]
    lines.extend("| " + " | ".join(row) + " |" for row in rows)
    if column_relative_widths is None:
        return "\n".join(lines) + "\n"
    widths = ",".join(str(width) for width in column_relative_widths)
    return "\n".join(lines) + "\n" + f'\n: {{tbl-colwidths="[{widths}]"}}\n'


def export_assumptions(root: Path, config: dict) -> None:
    security = config["security_economics"]
    rows: list[dict] = []
    for path in security["normalized_price_paths"]:
        rows.append(
            {
                "category": "price path",
                "case_id": path["id"],
                "case_name": path["name"],
                "parameter": "annual price-index change / liquidity realization",
                "value": f"{path['annual_change_pct']}% / {path['liquidity_realization_pct']}%",
                "unit": "normalized sensitivity",
                "status": "illustrative, not forecast",
            }
        )
    for case in security["fee_cases"]:
        rows.append(
            {
                "category": "fees",
                "case_id": case["id"],
                "case_name": case["name"],
                "parameter": (
                    f"fee per block / annual change; basis: "
                    f"{case.get('basis', 'configured sensitivity')}"
                ),
                "value": f"{case['fee_per_block_base_units']} base units / {case['annual_change_pct']}%",
                "unit": "base units per block",
                "status": case.get(
                    "evidence_status",
                    "illustrative sensitivity, not observed",
                ),
            }
        )
    for hardware in security["hardware_classes"]:
        rows.append(
            {
                "category": "hardware",
                "case_id": hardware["id"],
                "case_name": hardware["name"],
                "parameter": "electricity + other operations + amortization",
                "value": (
                    f"{hardware['electricity_cost_index_per_year']} + "
                    f"{hardware['non_electric_operating_cost_index_per_year']} + "
                    f"{hardware['hardware_amortization_index_per_year']}"
                ),
                "unit": "normalized value per hashrate-index unit-year",
                "status": "placeholder class, not measured RinHash hardware",
            }
        )
    for response in security["entry_exit_sensitivity"]:
        rows.append(
            {
                "category": "miner response",
                "case_id": response["id"],
                "case_name": response["id"].title(),
                "parameter": "revenue elasticity / response lag",
                "value": f"{response['elasticity']} / {response['response_lag_days']} days",
                "unit": "normalized sensitivity",
                "status": "illustrative, not behavioral law",
            }
        )
    write_csv(root / "data" / f"{REVISION}security_assumptions.csv", rows)
    table_rows = [
        [row["category"], row["case_name"], row["parameter"], row["value"], row["unit"], row["status"]]
        for row in rows
    ]
    (root / "includes" / f"{REVISION}security_assumptions_table.qmd").write_text(
        generated_header(f"data/{REVISION}scenario_config.json")
        + md_table(
            ["Category", "Case", "Parameter", "Value", "Unit", "Status"],
            table_rows,
            ["left", "left", "left", "right", "left", "left"],
        ),
        encoding="utf-8",
    )


def export_boundary_shocks(
    root: Path, config: dict, scenarios: list[dict], built: dict[str, list[monetary.Segment]]
) -> None:
    activation = int(config["network"]["activation_height"])
    coin = int(config["network"]["coin_unit_base_units"])
    rows: list[dict] = []
    for scenario in scenarios:
        segments = built[scenario["id"]]
        boundaries = sorted({segment.start_height for segment in segments if segment.start_height >= activation})
        for height in boundaries:
            before = monetary.subsidy_at(segments, height - 1)
            after = monetary.subsidy_at(segments, height)
            change = after - before
            shock_pct = D(change) * D(100) / D(before) if before else D(0)
            rows.append(
                {
                    "scenario_id": scenario["id"],
                    "scenario_display_id": monetary.scenario_display_id(scenario),
                    "scenario_name": scenario["name"],
                    "boundary_height": height,
                    "subsidy_before_base_units": before,
                    "subsidy_after_base_units": after,
                    "subsidy_before_rin": fmt(monetary.rin(before, coin)),
                    "subsidy_after_rin": fmt(monetary.rin(after, coin)),
                    "nominal_change_base_units": change,
                    "nominal_revenue_shock_pct": fmt(shock_pct),
                    "fee_replacement_base_units_per_block": max(0, before - after),
                    "fee_replacement_rin_per_block": fmt(monetary.rin(max(0, before - after), coin)),
                    "boundary_type": "activation" if height == activation else "scheduled subsidy boundary",
                }
            )
    write_csv(root / "data" / f"{REVISION}reward_boundary_shocks.csv", rows)
    write_csv(
        root / "data" / f"{REVISION}fee_replacement_requirements.csv",
        [
            {
                "scenario_id": row["scenario_id"],
                "scenario_display_id": row["scenario_display_id"],
                "boundary_height": row["boundary_height"],
                "subsidy_before_rin": row["subsidy_before_rin"],
                "subsidy_after_rin": row["subsidy_after_rin"],
                "required_additional_fee_base_units_per_block": row["fee_replacement_base_units_per_block"],
                "required_additional_fee_rin_per_block": row["fee_replacement_rin_per_block"],
                "interpretation": "fee increase needed to hold nominal RIN/block revenue unchanged",
            }
            for row in rows
        ],
    )
    by_scenario: dict[str, list[dict]] = {}
    for row in rows:
        by_scenario.setdefault(row["scenario_id"], []).append(row)

    def normal_reduction_rate(scenario: dict) -> str:
        if scenario["kind"] in {"legacy_binary", "extended_epoch_binary_halving"}:
            return "50.00000000%"
        if scenario["kind"] in {
            "one_twentieth_no_floor",
            "one_twentieth_finite_floor",
            "one_twentieth_perpetual_floor",
        }:
            return "5.00000000%"
        if scenario["kind"] == "cap_derived_113_114":
            return fmt(D(100) / D(114)) + "%"
        return "phase-dependent"

    def largest_later_reduction(
        scenario_rows: list[dict], threshold_base_units: int
    ) -> tuple[str, str]:
        eligible = [
            row
            for row in scenario_rows
            if row["boundary_type"] != "activation"
            and int(row["subsidy_before_base_units"]) >= threshold_base_units
            and int(row["subsidy_after_base_units"])
            < int(row["subsidy_before_base_units"])
        ]
        if not eligible:
            return "n/a", "n/a"
        largest = min(
            eligible, key=lambda row: D(row["nominal_revenue_shock_pct"])
        )
        return (
            fmt(-D(largest["nominal_revenue_shock_pct"])) + "%",
            largest["boundary_height"],
        )

    metric_rows: list[dict] = []
    for scenario in scenarios:
        scenario_rows = by_scenario[scenario["id"]]
        activation_row = next(
            row for row in scenario_rows if row["boundary_type"] == "activation"
        )
        later = [
            row
            for row in scenario_rows
            if row["boundary_type"] != "activation"
        ]
        first_later = min(later, key=lambda row: int(row["boundary_height"]))
        one_rin = largest_later_reduction(scenario_rows, coin)
        point_one_rin = largest_later_reduction(scenario_rows, coin // 10)
        point_zero_one_rin = largest_later_reduction(
            scenario_rows, coin // 100
        )
        segments = built[scenario["id"]]
        zero_height = monetary.first_zero_height(segments)
        if zero_height is None:
            terminal_height = "n/a"
            terminal_before = "n/a"
            terminal_shock = "n/a"
            terminal_type = "none under configured unbounded schedule"
        else:
            terminal_height = str(zero_height)
            terminal_before = fmt(
                monetary.rin(
                    monetary.subsidy_at(segments, zero_height - 1), coin
                )
            )
            terminal_shock = "100.00000000%"
            terminal_type = (
                "predetermined fixed-phase termination"
                if scenario["kind"]
                in {"one_twentieth_finite_floor", "configured_phases"}
                else "integer-rounding exhaustion"
            )
        metric_rows.append(
            {
                "scenario_id": scenario["id"],
                "scenario_display_id": monetary.scenario_display_id(scenario),
                "scenario_name": scenario["name"],
                "immediate_miner_revenue_shock_pct": fmt(
                    -D(activation_row["nominal_revenue_shock_pct"])
                ),
                "first_later_reduction_height": first_later[
                    "boundary_height"
                ],
                "first_later_reduction_pct": fmt(
                    -D(first_later["nominal_revenue_shock_pct"])
                ),
                "normal_scheduled_reduction_rate": normal_reduction_rate(
                    scenario
                ),
                "largest_later_reduction_at_or_above_1_rin": one_rin[0],
                "height_of_largest_later_reduction_at_or_above_1_rin": one_rin[
                    1
                ],
                "largest_later_reduction_at_or_above_0_1_rin": point_one_rin[
                    0
                ],
                "height_of_largest_later_reduction_at_or_above_0_1_rin": point_one_rin[
                    1
                ],
                "largest_later_reduction_at_or_above_0_01_rin": point_zero_one_rin[
                    0
                ],
                "height_of_largest_later_reduction_at_or_above_0_01_rin": point_zero_one_rin[
                    1
                ],
                "terminal_integer_rounding_height": terminal_height,
                "terminal_pre_boundary_subsidy_rin": terminal_before,
                "terminal_transition_type": terminal_type,
                "terminal_transition_shock": terminal_shock,
                "terminal_integer_rounding_shock": (
                    terminal_shock
                    if terminal_type == "integer-rounding exhaustion"
                    else "n/a"
                ),
            }
        )
    write_csv(
        root / "data" / f"{REVISION}reward_shock_metrics.csv", metric_rows
    )
    (root / "includes" / f"{REVISION}reward_shock_metrics_table.qmd").write_text(
        generated_header(
            f"data/{REVISION}reward_boundary_shocks.csv and "
            f"data/{REVISION}reward_shock_metrics.csv"
        )
        + md_table(
            [
                "Scenario",
                "Normal reduction",
                "Largest later reduction, pre-subsidy >= 1 RIN",
                ">= 0.1 RIN",
                ">= 0.01 RIN",
                "Terminal transition",
            ],
            [
                [
                    row["scenario_display_id"],
                    row['normal_scheduled_reduction_rate'],
                    row['largest_later_reduction_at_or_above_1_rin'],
                    row['largest_later_reduction_at_or_above_0_1_rin'],
                    row['largest_later_reduction_at_or_above_0_01_rin'],
                    (
                        "n/a"
                        if row["terminal_transition_shock"] == "n/a"
                        else (
                            f"{row['terminal_pre_boundary_subsidy_rin']} RIN "
                            f"to zero at {int(row['terminal_integer_rounding_height']):,} "
                            f"({row['terminal_transition_shock']}; "
                            f"{row['terminal_transition_type']})"
                        )
                    ),
                ]
                for row in metric_rows
            ],
            ["center", "right", "right", "right", "right", "left"],
            column_relative_widths=[6, 15, 15, 15, 15, 34],
        ),
        encoding="utf-8",
    )

    stale_table = root / "includes" / f"{REVISION}largest_reward_shocks_table.qmd"
    if stale_table.exists():
        stale_table.unlink()


def export_miner_economics(
    root: Path, config: dict, scenarios: list[dict], built: dict[str, list[monetary.Segment]]
) -> None:
    net = config["network"]
    security = config["security_economics"]
    activation = int(net["activation_height"])
    bpy = int(net["blocks_per_year"])
    coin = int(net["coin_unit_base_units"])
    rows: list[dict] = []
    sustainable_rows: list[dict] = []
    comparison_rows: list[dict] = []
    for scenario in scenarios:
        segments = built[scenario["id"]]
        for years_int in security["horizon_years"]:
            years = D(years_int)
            height = activation + int(years * bpy)
            subsidy = monetary.subsidy_at(segments, height)
            for path in security["normalized_price_paths"]:
                p_index = price_index(path, years)
                realization = D(path["liquidity_realization_pct"]) / D(100)
                for fee_case in security["fee_cases"]:
                    fee = fee_base_units(fee_case, years)
                    block_revenue_units = subsidy + fee
                    annual_rin = monetary.rin(block_revenue_units * bpy, coin)
                    gross_value = annual_rin * p_index
                    realizable_value = gross_value * realization
                    fee_share = D(fee) * D(100) / D(block_revenue_units) if block_revenue_units else D(0)
                    for hardware in security["hardware_classes"]:
                        pool_multiplier = D(1) - D(hardware["pool_fee_pct"]) / D(100)
                        net_value = realizable_value * pool_multiplier
                        annual_cost = (
                            D(hardware["electricity_cost_index_per_year"])
                            + D(hardware["non_electric_operating_cost_index_per_year"])
                            + D(hardware["hardware_amortization_index_per_year"])
                        )
                        hashrate_index = net_value / annual_cost if annual_cost else D(0)
                        break_even_price = (
                            annual_cost / (annual_rin * realization * pool_multiplier)
                            if annual_rin and realization and pool_multiplier
                            else D(0)
                        )
                        common = {
                            "scenario_id": scenario["id"],
                            "scenario_display_id": monetary.scenario_display_id(scenario),
                            "horizon_years": years_int,
                            "height": height,
                            "price_path": path["id"],
                            "fee_case": fee_case["id"],
                            "hardware_class": hardware["id"],
                            "subsidy_base_units": subsidy,
                            "fee_base_units_per_block": fee,
                            "fee_share_of_gross_rin_revenue_pct": fmt(fee_share),
                            "annual_gross_miner_revenue_rin": fmt(annual_rin),
                            "normalized_price_index": fmt(p_index),
                            "liquidity_realization_pct": path["liquidity_realization_pct"],
                            "annual_gross_miner_revenue_value_index": fmt(gross_value),
                            "annual_realizable_miner_revenue_value_index": fmt(realizable_value),
                            "normalized_annual_break_even_cost": fmt(annual_cost),
                            "break_even_price_index": fmt(break_even_price),
                        }
                        rows.append(common)
                        sustainable_rows.append(
                            {
                                **common,
                                "normalized_sustainable_hashrate_index": fmt(hashrate_index),
                                "interpretation": "revenue-supported normalized cost units; not measured hashrate",
                            }
                        )
                        if path["id"] == "flat" and fee_case["id"] == "base" and hardware["id"] == "reference":
                            comparison_rows.append(
                                {
                                    "scenario_id": scenario["id"],
                                    "scenario_display_id": monetary.scenario_display_id(scenario),
                                    "horizon_years": years_int,
                                    "height": height,
                                    "subsidy_rin_per_block": fmt(monetary.rin(subsidy, coin)),
                                    "fee_share_pct": fmt(fee_share),
                                    "annual_realizable_miner_revenue_index": fmt(realizable_value),
                                    "normalized_sustainable_hashrate_index": fmt(hashrate_index),
                                    "assumption_case": "flat price / base fee / reference hardware",
                                }
                            )
    write_csv(root / "data" / f"{REVISION}miner_revenue_break_even.csv", rows)
    write_csv(root / "data" / f"{REVISION}sustainable_hashrate_index.csv", sustainable_rows)
    write_csv(root / "data" / f"{REVISION}security_comparison_by_horizon.csv", comparison_rows)

    wanted = {1, 10, 25, 50}
    table_rows = [
        [
            row["scenario_display_id"],
            str(row["horizon_years"]),
            row["subsidy_rin_per_block"],
            row["fee_share_pct"],
            row["annual_realizable_miner_revenue_index"],
            row["normalized_sustainable_hashrate_index"],
        ]
        for row in comparison_rows
        if int(row["horizon_years"]) in wanted
    ]
    (root / "includes" / f"{REVISION}security_horizon_comparison_table.qmd").write_text(
        generated_header(f"data/{REVISION}security_comparison_by_horizon.csv")
        + md_table(
            ["Scenario", "Years", "Subsidy", "Fee share, %", "Revenue index", "Sustainable-hashrate index"],
            table_rows,
            ["center", "right", "right", "right", "right", "right"],
            column_relative_widths=[10, 10, 17, 20, 21, 22]
        ),
        encoding="utf-8",
    )


def export_attack_proxies(root: Path, config: dict) -> None:
    security = config["security_economics"]
    bpy = int(config["network"]["blocks_per_year"])
    comparison = read_csv(root / "data" / f"{REVISION}security_comparison_by_horizon.csv")
    rows: list[dict] = []
    for item in comparison:
        annual_revenue = D(item["annual_realizable_miner_revenue_index"])
        sustainable = D(item["normalized_sustainable_hashrate_index"])
        for duration in security["attack_proxy"]["durations_blocks"]:
            duration_years = D(duration) / D(bpy)
            for share_text in security["attack_proxy"]["redirectable_hash_shares_pct"]:
                share = D(share_text) / D(100)
                redirected = annual_revenue * duration_years * share
                owned_electricity = sustainable * D("0.40") * duration_years * share
                rows.append(
                    {
                        "scenario_id": item["scenario_id"],
                        "scenario_display_id": item["scenario_display_id"],
                        "horizon_years": item["horizon_years"],
                        "attack_duration_blocks": duration,
                        "redirectable_hash_share_pct": share_text,
                        "redirected_hash_opportunity_cost_proxy": fmt(redirected, 12),
                        "owned_hardware_electricity_cost_proxy": fmt(owned_electricity, 12),
                        "possible_double_spend_value": "not inferred; configured hypothetical values are separate",
                        "rental_market_assumption": security["attack_proxy"]["rental_market_status"],
                    }
                )
    write_csv(root / "data" / f"{REVISION}attack_cost_proxies.csv", rows)


def export_figures(root: Path, config: dict, scenarios: list[dict]) -> None:
    comparison = read_csv(root / "data" / f"{REVISION}security_comparison_by_horizon.csv")
    colors = {item["id"]: tuple(item["color"]) for item in scenarios}
    names = {item["id"]: monetary.scenario_label(item) for item in scenarios}
    selected = set(config["security_economics"]["comparison_scenarios"])

    def series_for(column: str, max_year: int):
        result = []
        for scenario_id in selected:
            points = [
                (float(row["horizon_years"]), float(row[column]))
                for row in comparison
                if row["scenario_id"] == scenario_id and int(row["horizon_years"]) <= max_year
            ]
            result.append((names[scenario_id], colors[scenario_id], points))
        return result

    for years in (10, 25, 50):
        monetary.draw_line_chart(
            root / "figures" / f"{REVISION}security_revenue_index_{years}y.png",
            f"Normalized realizable miner revenue - first {years} years",
            "Normalized annual value index",
            series_for("annual_realizable_miner_revenue_index", years),
        )
        monetary.draw_line_chart(
            root / "figures" / f"{REVISION}security_hashrate_index_{years}y.png",
            f"Normalized sustainable-hashrate index - first {years} years",
            "Revenue-supported cost units",
            series_for("normalized_sustainable_hashrate_index", years),
        )
    monetary.draw_line_chart(
        root / "figures" / f"{REVISION}security_fee_share_50y.png",
        "Fee share of gross RIN-denominated miner revenue - first 50 years",
        "Percent",
        series_for("fee_share_pct", 50),
    )


def validate(root: Path, config: dict, built: dict[str, list[monetary.Segment]]) -> None:
    activation = int(config["network"]["activation_height"])
    shocks = read_csv(root / "data" / f"{REVISION}reward_boundary_shocks.csv")
    shock_keys = {(row["scenario_id"], int(row["boundary_height"])) for row in shocks}
    for scenario_id, segments in built.items():
        for segment in segments:
            if segment.start_height >= activation:
                assert (scenario_id, segment.start_height) in shock_keys

    monetary_summary_before = (root / "data" / f"{REVISION}scenario_summary.csv").read_bytes()
    required = [
        f"{REVISION}security_assumptions.csv",
        f"{REVISION}reward_boundary_shocks.csv",
        f"{REVISION}fee_replacement_requirements.csv",
        f"{REVISION}miner_revenue_break_even.csv",
        f"{REVISION}sustainable_hashrate_index.csv",
        f"{REVISION}attack_cost_proxies.csv",
        f"{REVISION}security_comparison_by_horizon.csv",
    ]
    for name in required:
        assert (root / "data" / name).stat().st_size > 0
    assert monetary_summary_before == (root / "data" / f"{REVISION}scenario_summary.csv").read_bytes()

    include = (root / "includes" / f"{REVISION}security_horizon_comparison_table.qmd").read_text(encoding="utf-8")
    central = read_csv(root / "data" / f"{REVISION}security_comparison_by_horizon.csv")
    assert next(row["annual_realizable_miner_revenue_index"] for row in central if row["scenario_id"] == "S1" and row["horizon_years"] == "10") in include


def main() -> None:
    root = Path.cwd()
    config = monetary.load_config(root)
    scenarios = config["scenarios"]
    built = {scenario["id"]: monetary.build_segments(config, scenario) for scenario in scenarios}
    monetary.run_assertions(config, built)
    export_assumptions(root, config)
    export_boundary_shocks(root, config, scenarios, built)
    export_miner_economics(root, config, scenarios, built)
    export_attack_proxies(root, config)
    export_figures(root, config, scenarios)
    validate(root, config, built)


if __name__ == "__main__":
    main()
