#!/usr/bin/env python3
"""Generate the two small table fragments S6B_Consensus_Testing_Summary.qmd
includes. Spot-check heights are cross-checked directly against
analysis/data/S6B_normative_test_vectors.csv (read, not re-derived); the
results-summary numbers are transcribed from the actually-executed test runs
recorded in S6B/unit-test-results.md and S6B/functional-test-results.md, not
computed here -- this script only formats them.
"""
import csv
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
VECTORS = ROOT / "analysis" / "data" / "S6B_normative_test_vectors.csv"
INCLUDES = ROOT / "verification" / "includes"

HEADER = "<!-- Generated by scripts/generate_s6b_summary_tables.py. Do not edit by hand. -->\n\n"

SPOTCHECK_HEIGHTS = {839999, 840000, 2100000, 4200000, 6300000, 234587499, 234587500}


def write_spotcheck_table():
    rows = []
    with open(VECTORS, newline="", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            h = int(r["height"])
            if h in SPOTCHECK_HEIGHTS:
                rows.append((h, r["vector_id"], r["maximum_subsidy_base_units"], r["notes"]))
    rows.sort()

    lines = [HEADER]
    lines.append("| Height | Vector ID | CSV value (base units) | C++ unit test result | Note |")
    lines.append("| ---: | --- | ---: | ---: | --- |")
    for h, vid, val, note in rows:
        lines.append(f"| {h:,} | {vid} | {int(val):,} | {int(val):,} — match | {note} |")
    (INCLUDES / "s6b_vector_spotcheck_table.qmd").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_results_summary_table():
    rows = [
        ("C++ unit tests", "532 / 532", "Done"),
        ("Fork scenario functional tests (single- and two-node)", "6 / 6", "Done"),
        ("Full functional CI allowlist (fork + pre-existing, unmodified)", "159 / 159", "Done"),
        ("Independent terminal-height/ceiling verification (pre-existing script, reused)", "exact match", "Done"),
        ("Third-party implementation design review (rincoin-core/rincoin@v1.1)", "reviewed, not adopted as-is", "Done"),
        ("Cross-implementation producer x validator matrix", "not yet run", "Outstanding"),
        ("Fuzz targets (commitment parsing, sig_fork_id sighash mixing)", "not yet written", "Outstanding"),
        ("Pool / seeder integration rehearsal", "not yet run", "Outstanding"),
        ("Push to rincoin-community/rincoin-core + CI run", "not yet done", "Outstanding"),
    ]
    lines = [HEADER]
    lines.append("| Evidence layer | Result | Status |")
    lines.append("| --- | ---: | --- |")
    for name, result, status in rows:
        lines.append(f"| {name} | {result} | {status} |")
    (INCLUDES / "s6b_results_summary_table.qmd").write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    write_spotcheck_table()
    write_results_summary_table()
    print("wrote includes/s6b_vector_spotcheck_table.qmd and includes/s6b_results_summary_table.qmd")
